#!/bin/sh

if [ -z "$http_proxy" ]; then
	java -jar /usr/lib/josm/josm.jar
else
	proxy_port=`echo $http_proxy|sed -e 's/.*://g'`
	proxy_host=`echo $http_proxy|sed -e 's!.*://\(.*\):.*!\1!g'`
	java -Dhttp.proxyHost=$proxy_host -Dhttp.proxyPort=$proxy_port -jar /usr/lib/josm/josm.jar
fi
