"action_createpoi": creating a POI
"hint_pointselected": point selected\n(shift-click point to\nstart new line)
"action_movepoint": moving a point
"hint_drawmode": click to add point\ndouble-click/Return\nto end line
"hint_overendpoint": over endpoint\nclick to join\nshift-click to merge
"hint_overpoint": over point\nclick to join"
"gpxpleasewait": Please wait while the GPX track is processed.
"revert": Revert
"cancel": Cancel
"prompt_revertversion": "Revert to an earlier saved version:"
"tip_revertversion": Choose the version to revert to
"action_movepoi": moving a POI
"tip_splitway": Split way at selected point (X)
"tip_direction": Direction of way - click to reverse
"tip_clockwise": Clockwise circular way - click to reverse
"tip_anticlockwise": Anti-clockwise circular way - click to reverse
"tip_noundo": Nothing to undo
"action_mergeways": merging two ways
"tip_gps": Show GPS tracks (G)
"tip_options": Set options (choose the map background)
"tip_addtag": Add a new tag
"tip_addrelation": Add to a relation
"tip_repeattag": Repeat tags from the previously selected way (R)
"tip_alert": An error occurred - click for details
"hint_toolong": "too long to unlock:\nplease split into\nshorter ways"
"hint_loading": loading ways
"prompt_welcome": Welcome to OpenStreetMap!
"prompt_introduction": "Choose a button below to get editing. If you click 'Start', you'll be editing the main map directly - changes usually show up every Thursday. If you click 'Play', your changes won't be saved, so you can practise editing.\n\nRemember the golden rules of OpenStreetMap:\n\n"
"prompt_dontcopy": "Don't copy from other maps"
"prompt_accuracy": "Accuracy is important - only map places you've been"
"prompt_enjoy": And have fun!
"dontshowagain": "Don't show this message again"
"prompt_start": Start mapping with OpenStreetMap.
"prompt_practise": "Practice mapping - your changes won't be saved."
"practicemode": Practice mode
"help": Help
"prompt_help": Find out how to use Potlatch, this map editor.
"track": Track
"prompt_track": Convert your GPS track to (locked) ways for editing.
"action_deletepoint": deleting a point
"deleting": deleting
"action_cancelchanges": cancelling changes to
"emailauthor": \n\nPlease e-mail richard\@systemeD.net with a bug report, saying what you were doing at the time.
"error_connectionfailed": "Sorry - the connection to the OpenStreetMap server failed. Any recent changes have not been saved.\n\nWould you like to try again?"
"option_background": "Background:"
"option_fadebackground": Fade background
"option_thinlines": Use thin lines at all scales
"option_custompointers": Use pen and hand pointers
"tip_presettype": Choose what type of presets are offered in the menu.
"action_waytags": setting tags on a way
"action_pointtags": setting tags on a point
"action_poitags": setting tags on a POI
"action_addpoint": adding a node to the end of a way
"add": Add
"prompt_addtorelation": Add $1 to a relation
"prompt_selectrelation": Select an existing relation to add to, or create a new relation.
"createrelation": Create a new relation
"tip_selectrelation": Add to the chosen route
"action_reverseway": reversing a way
"tip_undo": Undo $1 (Z)
"error_noway": "Way $1 cannot be found (perhaps you've panned away?) so I can't undo."
"error_nosharedpoint": "Ways $1 and $2 don't share a common point any more, so I can't undo the split."
"error_nopoi": "The POI cannot be found (perhaps you've panned away?) so I can't undo."
"prompt_taggedpoints": Some of the points on this way are tagged. Really delete?
"action_insertnode": adding a node into a way
"action_splitway": splitting a way
"editingmap": Editing map
"start": Start
"play": Play
"delete": Delete
"a_way": $1 a way
"a_poi": $1 a POI
"action_moveway": moving a way
"way": Way
"point": Point
