######################################################################
# Automatically generated by qmake (2.01a) Mon May 18 20:33:40 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += osm-parse.cpp
