<!ENTITY background "#c1c1c1"> <!-- !!!"#b5d0d0" -->

<!ENTITY background_world "#eeedec"> <!-- !!!"#f2efe9" -->
<!ENTITY background_water "#c0c6c6"> <!-- !!!"#b5d0d0" -->

<!ENTITY motorway_stroke "#989fa8"> <!-- !!!"#809bc0" -->
<!ENTITY trunk_stroke "#bcc8bc"> <!-- !!!"#a9dba9" -->
<!ENTITY trunk_hizoom_stroke "#bcc8bc"> <!-- !!!"#97d397" TODO! -->
<!ENTITY primary_stroke "#c2c2c2"> <!-- "#ec989a" -->
<!ENTITY secondary_stroke "#d2d2d2"> <!-- "#fed7a5" -->
<!ENTITY tertiary_stroke "#d9d9d9"> <!-- "#ffffb3" -->
<!ENTITY trunk_casing_stroke "#c2c2c2"> <!-- "#477147" TODO! -->
<!ENTITY trunk_tunnels_stroke "#c2c2c2"> <!-- "#cdeacd" TODO! -->

<!ENTITY footway "#b6b6b6"> <!-- "salmon" -->
<!ENTITY track_grade1 "#716143"> <!-- !!!"#b37700" -->
<!ENTITY track_grade3 "#60533a"> <!-- !!!"#996600" -->


<!ENTITY buildings "#b5b1b1"> <!-- !!!"#bca9a9" -->
<!ENTITY building_opacity "0.5">

<!-- leisure -->
<!ENTITY playground "#e6e6e6"> <!-- "#ccfff1" -->
<!ENTITY park "#e1e1e1"> <!-- "#b6fdb6" -->
<!ENTITY pitch "#aeaeae"> <!-- "#8ad3af" -->
<!ENTITY track "#a8a8a8"> <!-- "#74dcba" -->
<!ENTITY grass "#cacaca"> <!-- "#cfeca8" -->
<!ENTITY sport_grounds "#a0a0a0"> <!-- eigentlich: "#0d9386", original: "#33cc99" -->


<!-- landuse -->
<!ENTITY retail "#e5e5e5"> <!-- "#f1dada" -->
<!ENTITY residential "#dddddd"> <!-- "#ddd" -->
<!ENTITY commercial "#dbdbdb"> <!-- "#efc8c8" -->
<!ENTITY industrial "#dad6d8"> <!-- !!!"#dfd1d6" -->
<!ENTITY wood "#b6bfb3"> <!-- !!!"#aed1a0" -->
<!ENTITY allotments "#aea99e"> <!-- !!!"#c8b084" -->
<!ENTITY brownfield "#8b8b7f"> <!-- !!!"#9d9d6c" -->
<!ENTITY forest "#96a48e"> <!-- !!!"#8dc56c" -->
<!ENTITY military "#dfc9c9"> <!-- !!!"#ffa8a8" -->
<!ENTITY vineyard "#b7c4b2"> <!-- !!!"#abdf96" -->
<!ENTITY farm "#d9d5cf"> <!-- !!!"#ead8bd" -->



<!-- amenity -->
<!ENTITY school "#e4e4e4"> <!-- "#f0f0d8" -->
        


<!ENTITY pa_free "#7fff00">
<!ENTITY pa_free_stroke "#1f9f00">
<!ENTITY pa_fee "#67a1eb">
<!ENTITY pa_fee_stroke "#3974dd">
<!ENTITY pa_customers "#b68529">
<!ENTITY pa_customers_stroke "#56250a">
<!ENTITY pa_residents "#785534">
<!ENTITY pa_residents_stroke "#1e150d">
<!ENTITY pa_private "#3f2920">
<!ENTITY pa_private_stroke "#0f0a08">
<!ENTITY pa_unknown "#70c78b">
<!ENTITY pa_unknown_stroke "#1c672b">

<!ENTITY pa_stroke_width "0.8">


<!ENTITY pa_stroke_opacity "1">
<!ENTITY pa_fill_opacity "1">
<!ENTITY pa_stroke_opacity_semi "0.5">
<!ENTITY pa_fill_opacity_semi "0.5">
