using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyCompanyAttribute("Igor Brejc and others")]
[assembly: AssemblyProductAttribute("Srtm2Osm")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2007-2012 Igor Brejc and others")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyFileVersionAttribute("1.8.2907.3")]
[assembly: AssemblyInformationalVersionAttribute("1.8")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyKeyNameAttribute("")]

