#!/bin/bash
#
# This script copies the eruby, ruby, html, css and images
# to the right places on www.openstreetmap

ROOT=/var/www/openstreetmap/

# eruby
cp ruby/editing-interface/*.rhtml $ROOT/eruby/

# includes for eruby
cp ruby/editing-interface/include/*.rhtml $ROOT/eruby/include/

# html

cp html/index.html $ROOT

# css

cp html/css/style.css $ROOT/css/

#images FIXME



# applet

cp java/dist/OSMApplet.jar $ROOT/edit/OSMApplet.jar
cp java/lib/commons-codec-1.3.jar $ROOT/edit/
cp java/dist/commons-httpclient-3.0-rc3.jar $ROOT/edit/
cp java/dist/commons-logging.jar $ROOT/edit/
cp java/dist/MinML2.jar $ROOT/edit/
cp java/dist/core.jar $ROOT/edit/
cp java/lib/applet-test.html $ROOT/edit/

# REST

cp ruby/api/*.rb $ROOT/ruby/api/0.2/
cp ruby/api/osm/*.rb $ROOT/ruby/api/0.2/osm/

# Apache simple-auth for REST
cp ruby/api/apache/simple-auth.rb /var/www/openstreetmap/ruby/api/apache/

# GPX RSS maker

cp ruby/rss/gpx_files.rb ../bin/

# GPX parser

cp ruby/editing-interface/support/insert_gpx_files.rb ../bin/

