#!/bin/bash

# Execute this script and you get a directory deploy/ with symbolic links
# Then copy the directory anywhere


CURDIR=`pwd`

echo "clean old"
rm -rf deploy

echo "link new"
mkdir -p deploy/eruby/include
for i in $CURDIR/ruby/editing-interface/*.rhtml; do ln -s $i deploy/eruby/; done
for i in $CURDIR/ruby/editing-interface/include/*.rhtml; do ln -s $i deploy/eruby/include/; done

mkdir deploy/css
for i in $CURDIR/html/css/*.css; do ln -s $i deploy/css/; done
for i in $CURDIR/html/images/*.gif; do ln -s $i deploy/css/; done

mkdir deploy/javascript
for i in $CURDIR/javascript/*; do ln -s $i deploy/javascript/; done

mkdir deploy/images
for i in $CURDIR/html/images/*; do ln -s $i deploy/images/; done


# API
mkdir -p deploy/ruby/api/0.3
for i in $CURDIR/ruby/api/*.rb; do ln -s $i deploy/ruby/api/0.3/; done
mkdir deploy/ruby/api/osm
for i in $CURDIR/ruby/api/osm/*.rb; do ln -s $i deploy/ruby/api/osm/; done
cd deploy/ruby; ln -s api/osm osm; cd ../..
mkdir deploy/ruby/api/apache
for i in $CURDIR/ruby/api/apache/*.rb; do ln -s $i deploy/ruby/api/apache/; done

cp $CURDIR/ruby/api/osm/servinfo.rb-TESTSERVER deploy/ruby/api/osm/servinfo.rb


for i in $CURDIR/ruby/rss/*.rb; do ln -s $i deploy/ruby/; done

# link applet
for i in $CURDIR/java/dist/*.jar; do ln -s $i deploy/; done
