#!/bin/bash
#
# This script copies the eruby, ruby, html, css and images
# to the right places on www.openstreetmap

ROOT=/var/www/openstreetmap/

# eruby
cp ruby/editing-interface/*.rhtml $ROOT/eruby/

# includes for eruby
cp -r ruby/editing-interface/include $ROOT/eruby/

# html

cp html/index.html $ROOT

# css

cp html/css/style.css $ROOT

#images FIXME



# applet

cp java/dist/OSMApplet.jar $ROOT/edit/
cp java/dist/xmlrpc-2.0-beta.jar $ROOT/edit/
cp java/dist/commons-codec-1.3.jar $ROOT/edit/
cp java/dist/core.jar $ROOT/edit/



