"action_createpoi": creare punct de interes (POI)
"hint_pointselected": Punctul selectat\n(shift-click pe punct pentru\no linie nouă)
"action_movepoint": Mișcă un punct
"hint_drawmode": click pentru a adăuga un punct\ndouble-click/Return\npentru a termina linia
"hint_overendpoint": deasupra la endpoint\nclick to join\nshift-click to merge
"hint_overpoint": over point\nclick to join"
"gpxpleasewait": Please wait while the GPX track is processed.
"revert": Inversează
"cancel": Anuleaza
"prompt_revertversion": "Revert to an earlier saved version:"
"tip_revertversion": Choose the version to revert to
"action_movepoi": Miscă POI
"tip_splitway": Choose the version to revert to
