#!/bin/bash

# Generates the mapnik xml files and includes from
# their respective templates.

# Variable declarations on the form ${VAR} are substituted with
# the value of the corresponding enviroment variable VAR.

if [[ -z $TOPOSM_ENV_SET ]]; then
    echo "Error: TopOSM environment not set."
    exit 1
fi

for SRC in `ls *.templ include/*.templ`; do
    echo "Processing $SRC..."
    DST=`dirname $SRC`/`basename $SRC .templ`
    cat "$SRC" \
        | awk '{while(match($0,"[$]{[^}]*}")){var=substr($0,RSTART+2,RLENGTH -3);gsub("[$]{"var"}",ENVIRON[var])}}1' \
        > "$DST"
done
echo "Done."

