#!/bin/bash

if [[ -z $TOPOSM_ENV_SET ]]; then
    echo "Error: TopOSM environment not set."
    exit 1
fi

SETUPCMD="shp2pgsql -p -I -g way -W latin1"
IMPORTCMD="shp2pgsql -a -g way -W latin1"
DBCMD="psql -q -p $DB_PORT $DB_NAME $DB_USER"

# NOTE: The data type for fcode and ftype is changed because, for some
# reason, mapnik (silently) fails to filter on bigint columns.

# areas
PREP_TABLE=1
for SRCFILE in $NHD_DIR/nhdarhi*.shp; do
    if [ "$PREP_TABLE" ]; then 
	    echo "Creating ${NHD_TABLE_PREFIX}_area tables..."
	    $SETUPCMD "$SRCFILE" ${NHD_TABLE_PREFIX}_area | $DBCMD
	    $SETUPCMD "$SRCFILE" ${NHD_TABLE_PREFIX}_area_major | $DBCMD
    fi
    echo "Importing $SRCFILE..."
    $IMPORTCMD "$SRCFILE" ${NHD_TABLE_PREFIX}_area |  $DBCMD
    unset PREP_TABLE
done
echo "ALTER TABLE ${NHD_TABLE_PREFIX}_area ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | $DBCMD
echo "ALTER TABLE ${NHD_TABLE_PREFIX}_area_major ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | $DBCMD
echo "Extracting major areas..."
echo "INSERT INTO ${NHD_TABLE_PREFIX}_area_major SELECT * FROM ${NHD_TABLE_PREFIX}_area WHERE areasqkm > 1" | $DBCMD

# flowlines
PREP_TABLE=1
for SRCFILE in $NHD_DIR/nhdflh??.shp; do
    if [ "$PREP_TABLE" ]; then 
	    echo "Creating ${NHD_TABLE_PREFIX}_flowline table..."
	    $SETUPCMD "$SRCFILE" ${NHD_TABLE_PREFIX}_flowline | $DBCMD
	    $SETUPCMD "$SRCFILE" ${NHD_TABLE_PREFIX}_flowline_major | $DBCMD
    fi
    echo "Importing $SRCFILE..."
    $IMPORTCMD "$SRCFILE" ${NHD_TABLE_PREFIX}_flowline | $DBCMD
    unset PREP_TABLE
done
echo "ALTER TABLE ${NHD_TABLE_PREFIX}_flowline ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | $DBCMD
echo "Extracting major flowlines..."
echo "INSERT INTO ${NHD_TABLE_PREFIX}_flowline_major SELECT * FROM ${NHD_TABLE_PREFIX}_flowline WHERE lengthkm > 2" | $DBCMD

# points
PREP_TABLE=1
for SRCFILE in $NHD_DIR/nhdpthi*.shp; do
    if [ "$PREP_TABLE" ]; then 
	    echo "Creating ${NHD_TABLE_PREFIX}_point table..."
	    $SETUPCMD "$SRCFILE" ${NHD_TABLE_PREFIX}_point | $DBCMD
    fi
    echo "Importing $SRCFILE..."
    $IMPORTCMD "$SRCFILE" ${NHD_TABLE_PREFIX}_point | $DBCMD
    unset PREP_TABLE
done
echo "ALTER TABLE ${NHD_TABLE_PREFIX}_point ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | $DBCMD

# waterbodies
PREP_TABLE=1
for SRCFILE in $NHD_DIR/nhdwbhi*.shp; do
    if [ "$PREP_TABLE" ]; then 
	    echo "Creating ${NHD_TABLE_PREFIX}_waterbody table..."
	    $SETUPCMD "$SRCFILE" ${NHD_TABLE_PREFIX}_waterbody | $DBCMD
	    $SETUPCMD "$SRCFILE" ${NHD_TABLE_PREFIX}_waterbody_major | $DBCMD
    fi
    echo "Importing $SRCFILE..."
    $IMPORTCMD "$SRCFILE" ${NHD_TABLE_PREFIX}_waterbody | $DBCMD
    unset PREP_TABLE
done
echo "ALTER TABLE ${NHD_TABLE_PREFIX}_waterbody ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | $DBCMD
echo "Extracting major waterbodies..."
echo "INSERT INTO ${NHD_TABLE_PREFIX}_waterbody_major SELECT * FROM ${NHD_TABLE_PREFIX}_waterbody WHERE areasqkm > 1" | $DBCMD

echo "Done."
