#!/bin/bash

# Imports one or more planet dumps (*.osm.bz2, *.osm) or
# planet diffs (*.osc.gz, *.osc).

if [[ -z $TOPOSM_ENV_SET ]]; then
    echo "Error: TopOSM environment not set."
    exit 1
fi

if [ -z "$1" ]; then
    echo "Syntax: import_planet <file> [<file> ...]"
    exit 2
fi


DBCMD="psql -q -p $DB_PORT $DB_NAME $DB_USER"

# Import data files.
while [ $# -gt 0 ]; do
    SRCFILE="$1"
    
    # Find out whether to append to or create a new database.
    OPERATOR=""
    CAT=""
    case "$SRCFILE"
    in
        *.osm.bz2 | *.osm)
            echo "Importing planet dump $SRCFILE..."
            OPERATOR="-c" # (re)create tables
	    CAT="bzcat"
	        ;;
	    *.osc.gz | *.osc)
	        echo "Applying diff $SRCFILE..."
	        OPERATOR="-a" # append
		CAT="zcat"
	        ;;
	    *)
	        echo "Unknown file type: $SRCFILE"
	        exit 1
	        ;;
	esac
	
    # Make sure that the file exists.
	if [ ! -f "$SRCFILE" ]; then
	    echo "File not found: $SRCFILE"
	    exit 2
	fi

    # Import the file.
	$CAT "$SRCFILE" | \
        sed "s/v=\"coastline\"/v=\"cXline\"/g" | \
        osm2pgsql -m $OPERATOR --bbox "$EXTENTS_LATLON" \
          --style "$OSM2PGSQL_STYLE_FILE" -P $DB_PORT -d "$DB_NAME" \
          -U "$DB_USER" --prefix "$DB_PREFIX" \
          --slim -C 2000 -	

	shift
done

# Rename coastline tags back.
for SUFFIX in line point polygon roads; do
    echo "Renaming coastlines in ${DB_PREFIX}_${SUFFIX}..."
    echo "UPDATE ${DB_PREFIX}_${SUFFIX} SET \"natural\"='coastline' WHERE \"natural\"='cXline'" | $DBCMD
done


# Extract road numbers.

# TODO: This fails if column exists. Not a problem, but should be
# handled more gracefully.
echo "Adding road numbers column..."
echo "ALTER TABLE ${DB_PREFIX}_roads ADD COLUMN roadnumber VARCHAR(10);" | $DBCMD

# interstates
echo "UPDATE ${DB_PREFIX}_roads SET roadnumber = SUBSTRING(ref FROM 'I[ -]([0-9]+)') WHERE (highway = 'motorway' OR highway = 'trunk') AND (ref LIKE 'I %' OR ref LIKE 'I-%')" | $DBCMD
# US routes
echo "UPDATE ${DB_PREFIX}_roads SET roadnumber = SUBSTRING(ref FROM 'US ([0-9A-Z]+)') WHERE (highway <> '' AND highway IS NOT NULL) AND ref LIKE 'US %'" | $DBCMD
# state routes
echo "UPDATE ${DB_PREFIX}_roads SET roadnumber = SUBSTRING(ref FROM 'SR ([0-9A-Z]+)') WHERE (highway <> '' AND highway IS NOT NULL) AND ref LIKE 'SR %'" | $DBCMD
echo "UPDATE ${DB_PREFIX}_roads SET roadnumber = SUBSTRING(name FROM 'State Highway ([0-9A-Z]+)') WHERE (highway <> '' AND highway IS NOT NULL) AND name LIKE 'State Highway %'" | $DBCMD
# CO routes
echo "UPDATE ${DB_PREFIX}_roads SET roadnumber = SUBSTRING(ref FROM 'C ([0-9A-Z]+)') WHERE (highway <> '' AND highway IS NOT NULL) AND ref LIKE 'C %'" | $DBCMD

