"action_createpoi": vytváření bodu zájmu (POI)
"hint_pointselected": vybrán bod\n(shift-klik na bod\nzačne novou cestu)
"action_movepoint": posouvám bod
"hint_drawmode": přidej bod kliknutím\ndvojklik/Enter\nukončí cestu
"hint_overendpoint": "koncový bod:\nkliknutí pro napojení,\nshift-klik cesty sloučí"
"hint_overpoint": bod cesty:\nkliknutím cestu napojíte"
"gpxpleasewait": "Počkejte prosím: Zpracovávám GPX cestu"
"revert": Vrátit zpět
"cancel": Zrušit
"prompt_revertversion": "Vrátit se ke dříve uložené verzi:"
"tip_revertversion": "Vyberte verzi, ke které se chcete vrátit:"
"action_movepoi": posunutí bodu záju (POI)
"tip_splitway": Rozdělit cestu ve vybraném bodě (X)
"tip_direction": Směr cesty (kliknutím otočíte)
"tip_clockwise": Po směru hodinových ručiček (kliknutím otočíte směr kruhové cesty)
"tip_anticlockwise": Proti směru hodinových ručiček (kliknutím otočíte směr kruhové cesty)
"tip_noundo": Není, co vzít zpět
"action_mergeways": sloučení dvou cest
"tip_gps": Zobrazit GPX stopy (GPS logy) (G)
"tip_options": Možnosti (vyberte si mapu na pozadí)
"tip_addtag": Přidat tag
"tip_addrelation": Přidat do relace
"tip_repeattag": Nastavit tagy předtím vybrané cesty(R)
"tip_alert": Vyskyla se chyba - pro více informací klikněte
"hint_toolong": "cesta je příliš dlouhá:\nrozdělte cestu na několik\nkratších úseků"
"hint_loading": načítám cesty
"prompt_welcome": Vítejte na OpenStreetMap
"prompt_introduction": "Klikněte jedno z tlačítek níže. Kliknutím na 'Start' začnete rovnou editovat mapu - změny se  projeví většinou při pravidelné úterní aktualizaci. Tlačítko 'Pískoviště' nastaví tréninkový režim, kdy se vaše změny nebudou ukládat a vy si budete moci editaci vyzkoušet na nečisto.\n\nTři hlavní pravidla projektu OpenStreetMap:\n\n"
"prompt_dontcopy": Nekopírujte z ostatních map - neporušujte autorská práva
"prompt_accuracy": Buďtě přesní - mapujte jen místa, kde jste skutečně byli
"prompt_enjoy": A hlavně, bavte se!
"dontshowagain": Příště tuto zprávu nezobrazovat
"prompt_start": Začít editovat
"prompt_practise": Tréninkový mód - změny se nebudou ukládat.
"practicemode": Tréninkový mód
"help": Nápověda
"prompt_help": Seznamte se s Potlatchem, tímto mapovým editorem
"track": Trasovat
"prompt_track": Převede vaši GPS stopu na (uzamčené) cesty, které následně můžete upravit.
"action_deletepoint": odstraňuji bod
"deleting": deleting
"action_cancelchanges": cancelling changes to
"emailauthor": \n\nProsím pošlete e-mail na richard\@systemeD.net s bug-reportem a popisem toho, co jste právě dělali. Pokud nemluvíte anglicky, napište na talk-cz\@openstreetmap.org
"error_connectionfailed": "Spojení s OpenStreetMap serverem selhalo. Vaše nedávné změny nemohly být uloženy.\n\nZkusit uložit změny znovu?"
"option_background": "Pozadí:"
"option_fadebackground": Zesvětlit pozadí
"option_thinlines": Používat tenké linky ve všech měřítkách mapy
"option_custompointers": Použít ukazatele kreslítka (pen) a ruky (hand)
"tip_presettype": Zvolit skupinu předvoleb v menu.
"action_waytags": úprava tagů cesty
"action_pointtags": nastavit tagy uzlu
"action_poitags": nastavit tagy bodu zájmu
"action_addpoint": přidávání uzlu na konec cesty
"add": Přidat
"prompt_addtorelation": Přidat $1 k relace
"prompt_selectrelation": Vyberte existující relaci, nebo vytvořte novou.
"createrelation": Vytvořit novou relaci
"tip_selectrelation": Přidat k vybrané cestě
"action_reverseway": reversing a way
"tip_undo": "Zpět: $1 (Z)"
"error_noway": Cesta $1 nebyla nalezena, takže nelze vrátit zpět (možná jste posunuli mapu?).
"error_nosharedpoint": Cesty $1 a $2 v současnosti nemaí společný bod, takže nemůžu vrátit zpět.
"error_nopoi": Bod zájmu nebyl nalezen, takže nelze vrátit zpět (možná jste posunuli mapu?).
"prompt_taggedpoints": Některé uzle této cesty mají tagy, opravdu smazat?
"action_insertnode": přidávání uzle do cesty
"action_splitway": rozděluji cestu
"editingmap": Editace mapy
"start": Start
"play": Přehrát
"delete": Smazat
"a_way": $1 cestu
"a_poi": $1 bod zájmu
"action_moveway": přesunout cestu
"way": Cesta
"point": Bod
"ok": Budiž
"existingrelation": Přidat k existující relaci
"findrelation": Najít relaci obsahující
"norelations": V aktuální datech není žádná relace
"advice_toolong": Příliš dlouhé pro odemčení - prosím rozdělte do kratších cest
"advice_waydragged": Cesta posunuta (Z pro odvolání změny)
"advice_tagconflict": Tagy nepasují - prosím zkontrolujte
"advice_nocommonpoint": Cesty nesdílí společný bod
"option_warnings": Zobrazovat plovoucí varování
"reverting": vracím zpět
"prompt_helpavailable": Nový uživatel editoru? Nápovědu najdete vpravo dole.
"prompt_editsave": Ukládat najednou
"prompt_editlive": Ukládat okamžitě
"launch": Otevřít
"prompt_launch": Otevřít externí webovou adresu?
"editinglive": "Režim editace: okamžité ukládání"
"openchangeset": Otevírám changeset
"editingoffline": "Režim editace: uložení najednou"
"save": Uložit změny
"drag_pois": Klikněte a přetáhněte body zájmu (POI)
"prompt_savechanges": Uložit změny
"prompt_changesetcomment": "Napište shrnutí provedených změn:"
