"action_createpoi": Skapa en POI, "punkt av intresse"
"hint_pointselected": En punkt är vald\n(Shift-klicka på punkten för att starta en ny väg)
"action_movepoint": Flytta en punkt
"hint_drawmode": Klicka för att lägga till en punkt\n Dubbelklicka för att avsluta vägen.
"hint_overendpoint": över en slutpunkt\nklicka för att sätta fast\nshift-klicka för att slå samman
"hint_overpoint": över en punkt\nklicka för att sätta fast"
"gpxpleasewait": GPX-loggen bearbetas, var god vänta.
"revert": Använd denna version
"cancel": Avbryt
"prompt_revertversion": Gå tillbaks till en tidigare version
"tip_revertversion": Välj version som ska användas
"action_movepoi": Flytta på en POI, "punkt av intresse"
"tip_splitway": Dela upp vägen i två delar vid den valda punkten (x)
"tip_direction": Vägens riktning - klicka för att vända vägen
"tip_clockwise": Vägen är rund, riktad medurs, klicka för att vända riktning
"tip_anticlockwise": Vägen är rund, riktad moturs, klicka för att vända riktning
"tip_noundo": Finns inget att ångra
"action_mergeways": Slå samman två vägar
"tip_gps": Visa GPS-spår (G)
"tip_options": Ändra inställningar (välj bakgrundskarta)
"tip_addtag": Lägg till en ny etikett (tag)
"tip_addrelation": Lägg till en ny relation
"tip_repeattag": Kopiera etiketterna (taggarna) från den senast valda vägen (R)
"tip_alert": Ett fel har inträffat - klicka för detaljer
"hint_toolong": "för lång för att låsa upp:\ndela upp vägen\ni mindre delar"
"hint_loading": laddar vägar
"prompt_welcome": Välkommen till OpenStreetMap!
"prompt_introduction": "För att börja editera, klicka på en av knapparna nedan. Om du klickar på 'Start' så arbetar du direkt mot huvudkartan, och ändringar sparas automatiskt - ändringarna syns normalt varje torsdag efter huvudkartan uppdaterats. Om du klickar 'Prova' så kommer inget att sparas, ett bra sätt att träna på att använda programmet.\n\nKom ihåg OpenStreetMaps gyllene regler:\n\n"
"prompt_dontcopy": Kopiera inget från andra kartor
"prompt_accuracy": Noggrannhet är viktigt - Ändra bara kartan på ställen du varit
"prompt_enjoy": och ha roligt!
"dontshowagain": Visa inte detta medelande igen
"prompt_start": Börja göra ändringar på OpenStreetMaps karta.
"prompt_practise": Träna på kartering - inga ändringar kommer att sparas.
"practicemode": Träningsläge
"help": Hjälp
"prompt_help": Information hur man använder Potlatch, den här karteditorn.
"track": Spår
"prompt_track": Omvandla dina GPS-spår till (låsta) vägar för editering.
"action_deletepoint": tar bort en punkt
"deleting": tar bort
"action_cancelchanges": avbryter ändringar på
"emailauthor": \n\nVänligen e-posta richard\@systemeD.net med en felrapport som beskriver vad du gjorde när felet inträffade.
"error_connectionfailed": "Tyvärr har vi tappat kontakten med OpenStreetMap serven. Nygjorda ändringar har inte kunnat sparas.\n\nFörsöka återansluta?"
"option_background": "Bakgrund:"
"option_fadebackground": Mattad bakgrund
"option_thinlines": Använd tunna linjer på alla skalor
"option_custompointers": Använd penna och handpekare
"tip_presettype": Välj vilka typer av inställningar som syns i menyn.
"action_waytags": lägger till taggar på en väg
"action_pointtags": lägger till taggar på en punkt
"action_poitags": lägger till taggar på en POI
"action_addpoint": lägger till en punkt på slutet av en väg
"add": Lägg till
"prompt_addtorelation": Lägg till $1 till en relation
"prompt_selectrelation": Välj en befintlig relation att addera till, eller skapa en ny relation.
"createrelation": Skapa en ny relation
"tip_selectrelation": Addera till den valda rutten
"action_reverseway": Byter rikting på en väg
"tip_undo": Ångra $1 (Z)
"error_noway": Vägen $1 kan inte hittas (du kanske har flyttat den utanför bilden?) så det går inte att ångra.
"error_nosharedpoint": Vägarna $1 och $2 möts inte i någon punkt längre, så det går inte att ångra delningen.
"error_nopoi": "POI:n kan inte hittas (du kanske har flyttat den utanför bilden?) så det går inte att ångra."
"prompt_taggedpoints": Några en punkterna i denna väg är taggade, vill du verkligen ta bort den?
"action_insertnode": lägger till en punkt till en väg
"action_splitway": delar upp en väg
"editingmap": Ändra online kartan
"start": Start
"play": Prova
"delete": Radera
"a_way": $1 en väg
"a_poi": $1 en POI
"action_moveway": flytta en väg
"way": Väg
"point": Nod (punkt)
"ok": Ok
"existingrelation": Lägg till existerande relation
"findrelation": Sök efter relation innehållande
"norelations": Inga relationer i nuvarande område
"advice_toolong": Det tog för lång tid att låsa upp - vänligen dela i kortare sträckor
"advice_waydragged": Hela sträckan flyttades (Z för att ångra)
"advice_tagconflict": Etiketter (tag) matchar inte - vänligen kontrollera (Z för att ångra)
"advice_nocommonpoint": Sträckorna har ingen gemensam nod
"option_warnings": Visa flytande varningar
"reverting": faller tillbaka
"prompt_helpavailable": Ny användare? Titta längst ner till vänster för hjälp.
"prompt_editsave": "Ändra via spara (Ändringar sparas när du klickar 'spara')"
"prompt_editlive": Ändra live (Alla ändringar sparas i och med att de utförs)
"launch": Starta
"prompt_launch": Öppna extern URL
"editinglive": Ändrar live
"openchangeset": Öppnar ändringsset
"editingoffline": Editerar offline
"save": Spara
"drag_pois": Drag och släpp intressepunkter (POI)
"prompt_savechanges": Spara ändringar
"prompt_changesetcomment": "Ange en beskrivning av dina ändringar:"
