# This script will download rana on a machine without SVN available

# Rana itself
wget --recursive -np -q -nH --cut-dirs=2 http://svn.openstreetmap.org/applications/mobile/rana/

# Dependancy on pyroute
wget --recursive --no-parent -q -nH --cut-dirs=2 --directory-prefix=rana/modules http://svn.openstreetmap.org/applications/routing/pyroutelib2/

# Dependancy on pyrender
wget --recursive --no-parent -q -nH --cut-dirs=2 --directory-prefix=rana/modules http://svn.openstreetmap.org/applications/rendering/pyrender/

# Remove anything generated by SVN web interface
find rana -name index.html | xargs rm
