public class Grammar {
	static String grammar = "	<!ELEMENT MapFeatures (entry*)>\n"
			+ "\n"
			+ "	<!ELEMENT entry (filter,titel,description)>\n" 
			+ "\n"
			+ "	<!ELEMENT filter (restriction|filter)+>\n"
			+ "	<!ELEMENT titel (#PCDATA|valueof|br)* >\n"
			+ "	<!ELEMENT description (#PCDATA|valueof|br)* >\n" 
			+ "\n"
			+ "	<!ELEMENT restriction EMPTY>\n" 
			+ "	<!ELEMENT valueof EMPTY>\n"
			+ "	<!ELEMENT br EMPTY>\n" 
			+ "\n" 
			+ "\n"
			+ "	<!ATTLIST entry\n"
			+ "	   osmKey		CDATA    #REQUIRED\n"
			+ "	   osmValue		CDATA    #REQUIRED\n"
			+ "	   filename		CDATA    #REQUIRED\n"
			+ "	   image		CDATA    #REQUIRED\n"
			+ "	   name			CDATA    #REQUIRED\n"
			+ "	   imagesize	CDATA    #REQUIRED\n"
			+ "	   imageoffset	CDATA    #REQUIRED\n"
			+ "	>\n" 
			+ "\n"
			+ "	<!ATTLIST filter\n"
			+ "	   logical		CDATA    #REQUIRED\n"
			+ "	   negation		CDATA	 #IMPLIED\n"
			+ "	>\n" 
			+ "	<!ATTLIST restriction\n"
			+ "	   osmKey		CDATA    #REQUIRED\n"
			+ "	   osmValue		CDATA    #REQUIRED\n"
			+ "	   negation		CDATA	 #IMPLIED\n"
			+ "	>\n"
			+ "\n"
			+ "	<!ATTLIST valueof\n"
			+ "	   osmKey		CDATA    #REQUIRED\n"
			+ "	>\n";
public static String getGrammar() {
	return grammar;
}
}