<!ENTITY wa_free "#7fff00">
<!ENTITY wa_free_stroke "#1f9f00">
<!ENTITY wa_fee "#67a1eb">
<!ENTITY wa_fee_stroke "#3974dd">
<!ENTITY wa_customers "#b68529">
<!ENTITY wa_customers_stroke "#56250a">
<!ENTITY wa_none "#3f2920">
<!ENTITY wa_none_stroke "#0f0a08">
<!ENTITY wa_unknown "#bc73e2">
<!ENTITY wa_unknown_stroke "#31203a">

<!ENTITY wa_stroke_width "0.8">

<!ENTITY wa_stroke_opacity "0.5">
<!ENTITY wa_fill_opacity "0.5">
<!ENTITY wa_stroke_opacity_semi "0.5">
<!ENTITY wa_fill_opacity_semi "0.5">
