"action_createpoi": "Créer un POI (point d'intérêt)"
"hint_pointselected": Point sélectionné\n(Shift-clic sur le point pour\ncommencer une nouvelle ligne)
"action_movepoint": Déplacer un point
"hint_drawmode": Clic pour ajouter un point\nDouble-clic/Entrée pour terminer le chemin
"hint_overendpoint": Sur le dernier point du tracé\nClick pour joindre\nShift-click pour fusionner
"hint_overpoint": Point du dessus\nClick pour joindre
"gpxpleasewait": Veuillez patientez pendant le traitement de la trace GPX
"revert": Revenir
"cancel": Annuler
"prompt_revertversion": "Revenir à une version sauvegardée plus récente :"
"tip_revertversion": Choisissez la version vers laquelle revenir
"action_movepoi": Déplacer un POI
"tip_splitway": Scinder le chemin au point sélectionné (X)
"tip_direction": Direction du chemin - Cliquez pour inverser
"tip_clockwise": "Circulation dans le sens des aiguilles d'une montre - Cliquez pour inverser le sens"
"tip_anticlockwise": "Circulation dans le sens inverse des aiguilles d'une montre (trigonométrique) - Cliquez pour inverser le sens"
"tip_noundo": Rien à annuler
"action_mergeways": Joindre deux chemins
"tip_gps": Afficher les traces GPS (G)
"tip_options": "Options (choix de la carte d'arrière plan)"
"tip_addtag": Ajouter un nouveau tag
"tip_addrelation": Ajouter à une relation
"tip_repeattag": Recopier les informations du chemin sélectionné précédemment (R)
"tip_alert": Une erreur est survenue - Cliquez pour plus de détails
"hint_toolong": "Trop long pour débloquer la situation:\nScindez le chemin en chemins plus courts"
"hint_loading": Chargement des chemins en cours
"prompt_welcome": Bienvenue sur OpenStreetMap !
"prompt_introduction": "Choisissez un bouton ci-dessous pour commencer l'édition. Si vous cliquez sur 'Editer', vous éditerez directement la carte principale - les modifications sont visibles sur celle-ci généralement tous les jeudis. Si vous cliquez sur 'Essai', vos modifications ne seront pas enregistrées, ainsi vous pouvez vous exercer sans risques.\n\nEt gardez en tête ces règles d'or d'OpenStreetMap :\n\n"
"prompt_dontcopy": "Ne copiez pas d'autre cartes"
"prompt_accuracy": Précision importante - Éditez seulement les lieux que vous avez visités
"prompt_enjoy": Et amusez-vous bien !
"dontshowagain": Ne plus afficher ce message
"prompt_start": Commencer à cartographier dans Openstreetmap
"prompt_practise": "Essai de cartographie : vos changements ne seront pas pris en compte"
"practicemode": "Mode d'essai"
"help": Aide
"prompt_help": Découvrez comment utiliser Potlatch, cet éditeur de carte
"track": Trace
"prompt_track": "Conversion d'une trace GPS en chemin (verrouillé) pour l'édition"
"action_deletepoint": "Suppression d'un point"
"deleting": Supprimer
"action_cancelchanges": Annulation de la modification
"emailauthor": "\n\nMerci d'envoyer un e-mail a richard\@systemeD.net pour signaler ce bogue, en expliquant ce que vous faisiez quand il est survenu."
"error_connectionfailed": Désolé, la connexion au serveur OpenStreetMap a échoué. Vos changements récents ne sont pas enregistrés.\n\nVoulez-vous réessayer ?
"option_background": "Arrière-plan :"
"option_fadebackground": Arrière-plan éclairci
"option_thinlines": Utiliser un trait fin à toutes les échelles
"option_custompointers": Remplacer la souris par le Crayon et la Main
"tip_presettype": Sélectionner le type de paramètres proposés dans le menu de sélection.
"action_waytags": Paramétrer un chemin
"action_pointtags": Paramétrer un point
"action_poitags": Paramétrer un POI
"action_addpoint": "Ajout d'un point à la fin d'un chemin"
"add": Ajouter
"prompt_addtorelation": Ajouter $1 à la relation
"prompt_selectrelation": "Sélectionner une relation existante pour l'ajouter, ou créer une nouvelle relation."
"createrelation": Créer une nouvelle relation
"tip_selectrelation": Ajouter à la route choisie
"action_reverseway": Inverser le sens du chemin
"tip_undo": "Annuler l'opération $1 (Z)"
"error_noway": "Le chemin $1 n'a pas été trouvé, il ne peut être restauré à son état précédent."
"error_nosharedpoint": "Les chemins $1 et $2 n'ont plus de point en commun et ne peuvent donc pas être recollés : l'opération précédente de scindage ne peut être annulée."
"error_nopoi": "Le point d'intérêt (POI) n'est pas trouvé (éventuellement sur une autre page?), il ne peut être restauré."
"prompt_taggedpoints": Certains points de ce chemin sont tagués. Souhaitez-vous les supprimer?
"action_insertnode": Ajouter un point sur un chemin
"action_splitway": Scinder un chemin
"editingmap": Modifier la carte
"start": Édition
"play": Essai
"delete": Supprimer
"a_way": $1 un chemin
"a_poi": $1 un POI
"action_moveway": Déplacer un chemin
"way": Chemin
"point": Point
"ok": Ok
"existingrelation": Ajouter à une relation existante
"findrelation": Trouver une relation contenant
"norelations": "Aucune relation dans l'espace courant"
"advice_toolong": Trop long pour débloquer la situation - Scindez le chemin en chemins plus courts
"advice_waydragged": Chemin déplacé (Z pour annuler)
"advice_tagconflict": Les tags ne correspondent pas - Veuillez vérifier
"advice_nocommonpoint": Les chemins ne partagent pas de point commun
"option_warnings": Montrer les avertissements flottants
"reverting": annule
