"action_createpoi": POI 만들기
"hint_pointselected": 포인트 선택됨\n(새로운 라인을 생성하려면\n포인트에서 shift-click하세요)
"action_movepoint": 포인트를 이동
"hint_drawmode": 클릭하면 포인트를 추가\n더블 클릭 또는 리턴 키를 누르면\n라인을 끝냄
"hint_overendpoint": 마지막 포인트에서\n클릭하면 연결합니다\nshift-click하면 합칩니다.
"hint_overpoint": 포인트를 클릭하면 연결합니다.
"gpxpleasewait": GPX 트랙로그가 처리될때 까지 기다려주세요.
"revert": 되돌리기
"cancel": 취소
"prompt_revertversion": "이전에 저장된 버전으로 부터 되돌리기:"
"tip_revertversion": "되돌릴 버전 선택:"
"action_movepoi": POI 이동
"tip_splitway": 선택된 포인트에서 길을 나누기(split) (X)
"tip_direction": 길의 방향 - 클릭하면 방향 바꿈
"tip_clockwise": 시계방향 원형도로 - 클릭하면 방향 바꿈
"tip_anticlockwise": 시계반대방향 원형도로 - 클릭하면 방향 바꿈
"tip_noundo": undo할 것이 없음
"action_mergeways": 두 길을 합침(merge)
"tip_gps": GPS 트랙 보이기 (G)
"tip_options": 옵션 지정(지도 배경 선택)
"tip_addtag": 새로운 태그 추가
"tip_addrelation": relation에 추가
"tip_repeattag": 이전 선택된 도로의 태그들을 적용 (R)
"tip_alert": 에러 발생 - 클릭하면 상세 내용 보기
"hint_toolong": "unlock하기엔 너무 깁니다:\n짧은 길로 나눠주세요"
"hint_loading": 길을 가져옵니다
"prompt_welcome": OpenStreetMap에 오신 것을 환영합니다!
"prompt_introduction": "아래 버튼 중 하나를 골라 에디터를 선택하세요. 'Start'를 클릭하면 바로 지도 수정이 가능합니다 - 보통은 매주 목요일에 변경내용이 지도에 나타납니다. 'Play'를 클릭하면 에디터에서 변경한 내용이 저장되지 않으므로 지도 수정을 연습할 수 있습니다.\n\nOpenStreetMap의 주요 규칙들을 기억하세요:\n\n"
"prompt_dontcopy": 다른 지도를 복사해 오지 마십시오.
"prompt_accuracy": 정확도가 중요합니다 -- 귀하가 알거나 머물렀던 곳만 작업하세요.
"prompt_enjoy": 재밌는 지도 작성이 되시길!
"dontshowagain": 이 메시지를 다시 보이지 않음
"prompt_start": 지도 작성 시작.
"prompt_practise": 지도 작성 연습 -- 변경 내용은 저장되지 않습니다.
"practicemode": 연습하기
"help": 도움말
"prompt_help": Potlatch 사용법을 알아봅니다.
"track": Track
"prompt_track": GPS tracklog를 수정가능한 길(locked)로 변환
"action_deletepoint": 포인트를 삭제
"deleting": 삭제
"action_cancelchanges": "변경 내용 취소:"
"emailauthor": \n\n버그가 발견되면 richard\@systemeD.net 에게 email을 주십시오. 그리고 귀하가 무슨 작업을 하고 있는지 알려주세요.
"error_connectionfailed": "죄송합니다. OpenStreetMap 서버와의 연결이 실패했습니다. 최근 변경사항은 저장되지 않았습니다\n\n접속을 다시 시도하겠습니까?"
"option_background": "배경:"
"option_fadebackground": 흐린 배경
"option_thinlines": 모든 축적에서 가는 선을 사용
"option_custompointers": pen과 hand 마우스 포인터 사용
"tip_presettype": Choose what type of presets are offered in the menu.
"action_waytags": 길의 태그를 설정
"action_pointtags": 포인트의 태그를 설정
"action_poitags": POI의 태그를 설정
"action_addpoint": 길의 마지막에 새로운 node 추가
"add": 추가
"prompt_addtorelation": relation에 $1 추가
"prompt_selectrelation": Select an existing relation to add to, or create a new relation.
"createrelation": 새로운 relation 생성
"tip_selectrelation": Add to the chosen route
"action_reverseway": reversing a way
"tip_undo": Undo $1 (Z)
"error_noway": "길 $1 이 발견되지 않았습니다 (perhaps you've panned away?) so I can't undo."
"error_nosharedpoint": 길 $1 과 $2 은(는) 같은 포인트를 더이상 공유하지 않습니다. 길 나누기를 취소할 수 없습니다.
"error_nopoi": "POI를 찾을 수 없습니다. (perhaps you've panned away?) so I can't undo."
"prompt_taggedpoints": 길의 몇몇 포인트에 태그가 있습니다. 정말 삭제하겠습니까?
"action_insertnode": 길에 node를 추가
"action_splitway": 길을 나누기
"editingmap": 지도 수정
"start": 시작
"play": 연습
"delete": 삭제
"a_way": $1 a way
"a_poi": $1 a POI
"action_moveway": 길을 이동중
"way": 길
"point": 포인트
"ok": 확인
"existingrelation": Add to an existing relation
"findrelation": Find a relation containing
"norelations": 현재 영역에 relation이 없습니다.
"advice_toolong": unlock하기에 너무 깁니다. 길을 짧게 나누세요
"advice_waydragged": 길이 통째로 움직였습니다 (Z 키를 누르면 undo 됩니다)
"advice_tagconflict": 태그가 일치하지 않습니다 -- 살펴보세요
"advice_nocommonpoint": 길들이 같은 포인트를 공유하지 않았습니다.
"option_warnings": Show floating warnings
"reverting": reverting
