"action_createpoi": creatin a plase
"hint_pointselected": point selecteded\n(shift-clik point ta\nstaart new lien)
"action_movepoint": movin a point
"hint_drawmode": clik ta add point\ndouble-clik/Return\nto end lien
"hint_overendpoint": ovah endpoint\nclik ta join\nshift-clik ta merge
"hint_overpoint": "I'M OVAH UR POINT\nCLICKIN TO JOIN"
"gpxpleasewait": Pleez wayt whiel teh GPZ track iz processeded.
"revert": Revert
"cancel": Noes!
"prompt_revertversion": plz to chooes vershun
"tip_revertversion": Chooes teh verzhun ta revert ta
"action_movepoi": movin a plase
"tip_splitway": wai goes NOM NOM NOM at the noed (X)
"tip_direction": Direcshun uv wai - clik ta bakwadz
"tip_clockwise": Clockwyez circlar wai - clik ta bakwadz
"tip_anticlockwise": Anti-clockwyez circlar wai - clik ta bakwadz
"tip_noundo": I haz nuffin for undos
"action_mergeways": mergin bowf waiz
"tip_gps": Can haz GPZ trax (G)
"tip_options": Set optionz (chooes teh map bakgrownd)
"tip_addtag": Noo tag
"tip_addrelation": Add ta a relashun
"tip_repeattag": Previous tagz ar relavint to mai selecteded wai (R)
"tip_alert": OHNOES! Errorz! - clik foar detailz
"hint_toolong": "too lawng ta unlok:\npleaes spleet into\nshortah waiz"
"hint_loading": NOM NOM NOM
"prompt_welcome": welcum ta OPENSTREETMAP!
"prompt_introduction": "Clik ta getz editin. If yoo clik 'Staart', yoo'll b editin teh mane map - chanzes uzually show up evry Purrsdai! If yoo clik 'Plae', yur chanzes won't b saveded, sow yoo kan practies editin.\n\nCeiling Cat sais:\n\n"
"prompt_dontcopy": Copi frum uddah mapz? DO NOT WANT
"prompt_accuracy": Want acoracie - ownlee map placez yuv bein!
"prompt_enjoy": Adn can has cheezburger!
"dontshowagain": dis messig suxs. No more show
"prompt_start": staart mappin wif OPENSTREETMAP.
"prompt_practise": Invisibl mappur - yur chanzes wont b saveded.
"practicemode": Practiec moeded
"help": Halp
"prompt_help": Find owt hao ta uz Potlatch, dis map editerer.
"track": Trak
"prompt_track": Convert yur GPZ track ta (lockeded) waiz foar editin.
"action_deletepoint": deletin a noed
"deleting": deletin
"action_cancelchanges": cancellin chanzes ta
"emailauthor": \n\NPLEAES e-male richard\@systemed.net wif a bug report, meaowin whut yoo werz doin at teh tyme.
"error_connectionfailed": "OHNOES! teh OPENSTREETMAP servah connecshun has a FAIL. I no saveded n e recent chanzes.\n\nYoo wants tri agin?"
"option_background": "bakground:"
"option_fadebackground": Faeded bakground
"option_thinlines": I can has thin linez at awl scalez
"option_custompointers": I can has pen adn paw pointerz
"tip_presettype": Chooes whut tyep uv presetz iz ofered in teh menu.
"action_waytags": In ur wai, settin teh tagz
"action_pointtags": In ur noed, settin teh tagz
"action_poitags": In ur plase, settin teh tagz
"action_addpoint": addin a noeded ta teh end uv a wai
"add": Add
"prompt_addtorelation": Add $1 ta a relashun
"prompt_selectrelation": Chooes a existin relashun ta add ta, or creaet a noo relashun.
"createrelation": Creaet a noo relashun
"tip_selectrelation": Add ta teh chosen rouet
"action_reverseway": reversin a wai
"tip_undo": Undo $1 (Z)
"error_noway": "I had a wai $1 but I losteded it, so noes can undo. :("
"error_nosharedpoint": waiz $1 adn $2 dun shaer a common point n e moar , sow I noes kan undo teh spleet.
"error_nopoi": "I had a plase but I losteded it, so noes can undo. :("
"prompt_taggedpoints": sum uv teh pointz awn dis wai iz taggeded. reelee deleet?
"action_insertnode": addin a noeded into a wai
"action_splitway": spleettin a wai
"editingmap": Editin map
"start": Staart
"play": Plae
"delete": Deleet
"a_way": $1 a wai
"a_poi": $1 A plase
"action_moveway": movin a wai
"way": Wai
"point": Noed
"ok": kthx
"existingrelation": Adds ta a relashun
"findrelation": Luks for a relashun wif
"norelations": I sees noes relashuns neer heer
