"action_createpoi": POI készítésének
"hint_pointselected": pont kijelölve\n(shift+kattintás a pontra\núj vonal kezdéséhez)
"action_movepoint": pont mozgatásának
"hint_drawmode": kattintás pont hozzáadásához\ndupla kattintás/Enter\na vonal befejezéséhez
"hint_overendpoint": végpont fölött\nkattintás a csatlakoztatáshoz\nshift+kattintás az egyesítéshez
"hint_overpoint": pont fölött\nkattintás a csatlakoztatáshoz
"gpxpleasewait": Kérlek, várj a GPX nyomvonal feldolgozásáig.
"revert": V.állít
"cancel": Mégse
"prompt_revertversion": "Visszaállítás egy korábbi mentett változatra:"
"tip_revertversion": Válaszd ki a változatot a visszaállításhoz
"action_movepoi": POI mozgatásának
"tip_splitway": Vonal kettévágása a kijelölt pontnál
"tip_direction": Vonal iránya - kattints a megfordításhoz
"tip_clockwise": Órajárással egyező körkörös vonal - kattints a megfordításhoz
"tip_anticlockwise": Órajárással ellentétes körkörös vonal - kattints a megfordításhoz
"tip_noundo": Nincs mit visszavonni
"action_mergeways": két vonal egyesítése
"tip_gps": GPS nyomvonalak megjelenítése
"tip_options": Beállítások módosítása (térképháttér kiválasztása)
"tip_addtag": Új címke hozzáadása
"tip_addrelation": Hozzáadás kapcsolathoz
"tip_repeattag": Az előzőleg kiválasztott vonal címkéinek megismétlése (R)
"tip_alert": Hiba történt - kattints a részletekért
"hint_toolong": "túl hosszú a feloldáshoz:\nkérlek, vágd szét\nrövidebb vonalakra"
"hint_loading": vonalak betöltése
"prompt_welcome": Üdvözöllek az OpenStreetMapon!
"prompt_introduction": "A szerkesztéshez válassz az alábbi gombok közül. Ha a 'Kezdés'-re kattintasz, akkor közvetlenül a főtérképet szerkesztheted - a módosítások általában minden csütörtökön jelennek meg. Ha a 'Próbá'-ra kattintasz, akkor a módosításaid nem lesznek elmentve, így gyakorolhatod a szerkesztést.\n\nEmlékezz az OpenStreetMap aranyszabályaira:\n\n"
"prompt_dontcopy": Ne másolj más térképekből
"prompt_accuracy": A pontosság fontos - csak olyan helyeket szerkessz, ahol már jártál
"prompt_enjoy": És jó szórakozást!
"dontshowagain": Ez az üzenet ne jelenjen meg újra
"prompt_start": Térképkészítés kezdése OpenStreetMappal.
"prompt_practise": Térképkészítés gyakorlása - módosításaid nem lesznek elmentve.
"practicemode": Gyakorló mód
"help": Súgó
"prompt_help": Nézz utána, hogyan kell használni a Potlatch-ot, ezt a térképszerkesztőt.
"track": Nyomvonal
"prompt_track": GPS nyomvonalaid átkonvertálása (zárolt) vonalakká a szerkesztéshez.
"action_deletepoint": pont törlésének
"deleting": törlés
"action_cancelchanges": Módosítások elvetése a következőre
"emailauthor": \n\nKérlek, jelentsd a hibát (angolul) a richard\@systemeD.net e-mail címre, és írd le, hogy mit csináltál akkor, amikor a hiba történt.
"error_connectionfailed": Bocs - az OpenStreetMap szerverhez való kapcsolódás sikertelen. A legutóbbi módosítások nem lettek elmentve.\n\nSzeretnéd megpróbálni újra?
"option_background": "Háttér:"
"option_fadebackground": Áttetsző háttér
"option_thinlines": Vékony vonalak használata minden méretaránynál
"option_custompointers": Toll és kéz egérmutatók használata
"tip_presettype": Válaszd ki, hogy milyen típusú sablonok legyenek a menüben.
"action_waytags": vonal címkéi állításának
"action_pointtags": pont címkéi állításának
"action_poitags": POI címkéi állításának
"action_addpoint": a vonal végéhez pont hozzáadásának
"add": Hozzáad
"prompt_addtorelation": $1 hozzáadása kapcsolathoz
"prompt_selectrelation": A hozzáadáshoz válassz egy meglévő kapcsolatot, vagy készíts egy újat.
"createrelation": Új kapcsolat létrehozása
"tip_selectrelation": Hozzáadás a kiválasztott kapcsolathoz
"action_reverseway": vonal megfordításának
"tip_undo": $1 visszavonása (Z)
"error_noway": A(z) $1 vonal nem található (talán már eltávolítottad?), így nem vonható vissza.
"error_nosharedpoint": Már nincs közös pontja a(z) $1 és a(z) $2 vonalaknak, így nem vonható vissza a kettévágás.
"error_nopoi": A POI nem található (talán már eltávolítottad?), így nem vonható vissza.
"prompt_taggedpoints": Ezen a vonalon van néhány címkézett pont. Biztosan törlöd?
"action_insertnode": vonalhoz pont hozzáadásának
"action_splitway": vonal kettévágásának
"editingmap": Szerkesztés
"start": Kezdés
"play": Próba
"delete": Törlés
"a_way": Vonal $1
"a_poi": POI $1
"action_moveway": vonal mozgatásának
"way": Vonal
"point": Pont
"ok": OK
"existingrelation": Hozzáadás egy meglévő kapcsolathoz
"findrelation": "Kapcsolat keresése, amely tartalmazza:"
"norelations": Nincs kapcsolat a jelenlegi területen
"advice_toolong": Túl hosszú a feloldáshoz - vágd rövidebb szakaszokra
"advice_waydragged": Vonal áthelyezve (Z a visszavonáshoz)
"advice_tagconflict": A címkék nem egyeznek - ellenőrizd (Z a visszavonáshoz)
"advice_nocommonpoint": A vonalaknak nincs közös pontjuk
"option_warnings": Lebegő figyelmeztetések megjelenítése
"reverting": visszaállítás
