<!ENTITY pa_free "#7fff00">
<!ENTITY pa_free_stroke "#1f9f00">
<!ENTITY pa_fee "#67a1eb">
<!ENTITY pa_fee_stroke "#3974dd">
<!ENTITY pa_customers "#b68529">
<!ENTITY pa_customers_stroke "#56250a">
<!ENTITY pa_residents "#785534">
<!ENTITY pa_residents_stroke "#1e150d">
<!ENTITY pa_private "#3f2920">
<!ENTITY pa_private_stroke "#0f0a08">
<!ENTITY pa_unknown "#bc73e2">
<!ENTITY pa_unknown_stroke "#31203a">

<!ENTITY pa_stroke_width "0.8">

<!ENTITY pa_stroke_opacity "0.5">
<!ENTITY pa_fill_opacity "0.5">
<!ENTITY pa_stroke_opacity_semi "0.5">
<!ENTITY pa_fill_opacity_semi "0.5">
