#!/usr/bin/python
#----------------------------------------------------------------
# Waypoint handler for pyroute
#
#------------------------------------------------------
# Copyright 2007, Oliver White
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------
from xml.sax import make_parser, handler

class Waypoints(handler.ContentHandler):
  def __init__(self):
    self.waypoints = []
    self.storeFields = ('name','sym')
    
  def load(self, filename):
    self.inField = False
    parser = make_parser()
    parser.setContentHandler(self)
    parser.parse(filename)
  
  def startElement(self, name, attrs):
    if name == "wpt":
      self.parsedWaypoint = { \
        'lat': float(attrs.get('lat')),
        'lon': float(attrs.get('lon'))}
    if name in self.storeFields:
      self.fieldText = ''
      self.inField = True
      
  def endElement(self, name):
    if self.inField:
      if name in self.storeFields:
        self.parsedWaypoint[name] = self.fieldText
      self.inField = False
    if(name == "wpt"):
      self.storeWaypoint(self.parsedWaypoint)
        
  def storeWaypoint(self, waypoint):
    self.waypoints.append(waypoint)
    
  def characters(self, text):
    if self.inField:
      self.fieldText = self.fieldText + text
    
  def report(self):
    for w in self.waypoints:
      print "%1.3f, %1.3f = %s (%s)" % (w['lat'], w['lon'], w['name'], w['sym'])
    
  def save(self, filename):
    f = open(filename, "w")
    f.write('<?xml version="1.0"?>\n')
    f.write('<gpx version="1.0" creator="pyroute">\n')
    #f.write('<time>2006-10-28T17:22:06Z</time>')
    for w in self.waypoints:
      f.write('<wpt lat="%f" lon="%f">\n' % (w['lat'], w['lon']))
      f.write('  <name>%s</name>\n' % w['name'])
      #f.write('  <cmt>%s</cmt>\n' % w['name'])
      #f.write('  <desc>%s</desc>\n' % w['name'])
      f.write('  <sym>%s</sym>\n' % w['sym'])
      f.write('</wpt>\n')
    f.write('</gpx>\n')
    f.close()

# Parse the supplied OSM file
if __name__ == "__main__":
  # Load the file generated by garmin
  wpt1 = Waypoints()
  wpt1.load("data/waypoints.gpx")
  # Save it
  wpt1.save("data/waypoints_output.gpx")

  # Try to load the file we saved, to check it's readable
  wpt2 = Waypoints()
  wpt2.load("data/waypoints_output.gpx")
  # And display the result on screen
  wpt2.report()
