"action_createpoi": POIを作成
"hint_pointselected": pointを選択\n(shiftキーを押しながらpointをクリックして\n新しいlineを開始)
"action_movepoint": pointを移動
"hint_drawmode": クリックしてpointを追加\nダブルクリック/Returnで\nline編集を終了
"hint_overendpoint": 終端のpoint上で\nクリックして接続\nshiftキーを押しながらクリックして結合
"hint_overpoint": point上で\nクリックして接続
"gpxpleasewait": GPX trackが処理されるまで暫くお待ち下さい。
"revert": 差し戻し
"cancel": 中止
"prompt_revertversion": "以前に保存されたバージョンに差し戻す:"
"tip_revertversion": 差し戻し先のバージョンを選択
"action_movepoi": POIを移動
"tip_splitway": 選択したpointでwayを分割 (X)
"tip_direction": wayの方向 - クリックして反転
"tip_clockwise": 時計回りのcircular way - クリックして反転
"tip_anticlockwise": 反時計回りのcircular way - クリックして反転
"tip_noundo": 取消対象無し
"action_mergeways": 2つのwayを結合
"tip_gps": GPS trackを表示 (G)
"tip_options": オプション設定 (地図背景の選択)
"tip_addtag": 新しいtagを追加
"tip_addrelation": relationへ追加
"tip_repeattag": 前回選択したwayのtagを繰り返す (R)
"tip_alert": エラーが発生しました。クリックすると詳細が表示されます。
"hint_toolong": "wayが長すぎるためunlockできません:\n短いwayに\n分割して下さい。"
"hint_loading": wayを読み込んでいます。
"prompt_welcome": OpenStreetMapへようこそ!
"prompt_introduction": "編集を開始する前に下のボタンを選択して下さい。 - 『開始』をクリックするとOSMの地図を直接編集します。通常では毎週木曜日に変更が表示されるようになります。 - 『練習』をクリックすると変更は保存されませんので、地図の編集作業を練習することができます。\n\nOpenStreetMapの鉄則を忘れないで下さい:\n\n"
"prompt_dontcopy": 他の地図から書き写してはいけません。
"prompt_accuracy": 正確さは大切です - 地図作りはあなたが行ったことのある場所だけにして下さい。
"prompt_enjoy": そして何より、楽しみましょう!
"dontshowagain": 次回からこのメッセージを表示しない。
"prompt_start": OpenStreetMapの地図の編集作業を開始します。
"prompt_practise": 地図の編集作業を練習します。 - あなたの変更は保存されません。
"practicemode": 練習モード
"help": ヘルプ
"prompt_help": この地図編集ソフトウェア(Potlatch)の使い方を表示します。
"track": 軌跡
"prompt_track": あなたのGPS trackを編集用のlockされたwayに変換します。
"action_deletepoint": pointを削除
"deleting": 削除
"action_cancelchanges": 変更を中止
"emailauthor": \n\nあなたがその時に何を行っていたかを書いたバグレポートを、 richard\@systemeD.net 宛てにe-mailで送付して下さい。
"error_connectionfailed": 申し訳ありません。OpenStreetMapのサーバーへの接続に失敗しました。 直近の変更は保存されていません。\n\n再送信しますか?
"option_background": "背景:"
"option_fadebackground": 背景を隠す
"option_thinlines": 全ての縮尺で細い線を使用する
"option_custompointers": ペンのポインターと手のポインターを使用する
"tip_presettype": 提供されているプリセットの種類をメニューから選択します。
"action_waytags": wayにtagを設定
"action_pointtags": pointにtagを設定
"action_poitags": POIにtagを設定
"action_addpoint": wayの終端にnodeを追加
"add": 追加
"prompt_addtorelation": relationに $1 を追加
"prompt_selectrelation": 追加又はrelationを新規作成するために既存のrelationを選択
"createrelation": 新しいrelationを作成
"tip_selectrelation": 選択したrouteへ追加
"action_reverseway": wayを反転
"tip_undo": $1 を取り消し (Z)
"error_noway": $1 というwayが見付からないため、取消ができませんでした。 (画面表示の範囲外になっていませんか?)
"error_nosharedpoint": $1 と $2 のwayは既に共通のpointを共有していないため、分割の取消ができませんでした。
"error_nopoi": 該当するPOIが見付からないため、取消ができませんでした。 (画面表示の範囲外になっていませんか?)
"prompt_taggedpoints": このwayに含まれているpointのいくつかにtagが付けられています。 本当に削除しますか?
"action_insertnode": wayの途中にnodeを追加
"action_splitway": wayを分割
"editingmap": 地図編集中
"start": 開始
"play": 練習
"delete": 削除
"a_way": wayを $1
"a_poi": POIを $1
"action_moveway": wayを移動
"way": Way
"point": Point
"ok": Ok
"existingrelation": 既存のリレーションを追加
"findrelation": 以下に含まれるリレーションを検索
"norelations": 現在のエリアにリレーションはありません
"advice_toolong": wayが長すぎるためunlockできません - 短いwayに分割して下さい。
"advice_waydragged": wayをドラッグしました。(Zでアンドゥ)
"advice_tagconflict": Tagが合ってません。 - 確認してください。(Zでアンドゥ)
"advice_nocommonpoint": そのwayは共通の点を持ってません。
"option_warnings": 吹き出し警告を表示する。
"reverting": リバート(差し戻し)
"prompt_helpavailable": 新しいユーザーですか? 左下にヘルプがあります。
"prompt_editsave": 保存と一緒に編集
"prompt_editlive": ライブ編集(保存しながら編集)
"launch": 起動
"prompt_launch": 外部URLを立ち上げる
"editinglive": ライブ編集
"openchangeset": Changeset を開いています。
"editingoffline": オフライン編集中
"save": 保存
"drag_pois": POIをドラッグ &amp; ドロップ
"prompt_savechanges": 変更を保存
"prompt_changesetcomment": "あなたの変更の説明を入力してください。:"
