#define AND_RD_TYPE_1  "highway","motorway"
#define AND_RD_TYPE_2  "highway","trunk"
#define AND_RD_TYPE_3  "highway","primary"
#define AND_RD_TYPE_4  "highway","secondary"
#define AND_RD_TYPE_5  "highway","tertiary"
#define AND_RD_TYPE_6  "highway","unclassified"
#define AND_RD_TYPE_7  "route","ferry;motorcars=yes;hgv=yes"
#define AND_RD_TYPE_9  "route","ferry;motorcars=no;foot=yes"
#define AND_RD_TYPE_30  "railway","rail"
#define AND_RD_TYPE_50  "highway","service"
#define AND_RD_TYPE_58  "highway","footway"
#define AND_RD_TYPE_59  "highway","virtual"

