<!ENTITY wa_free "#04c900">
<!ENTITY wa_free_stroke "#026600">
<!ENTITY wa_fee "#037afe">
<!ENTITY wa_fee_stroke "#023d80">
<!ENTITY wa_customers "#c17223">
<!ENTITY wa_customers_stroke "#623a12">
<!ENTITY wa_none "#634e45">
<!ENTITY wa_none_stroke "#332824">
<!ENTITY wa_unknown "#a649b7">
<!ENTITY wa_unknown_stroke "#52245b">

<!ENTITY wa_stroke_width "0.8">

<!ENTITY wa_stroke_opacity "0.5">
<!ENTITY wa_fill_opacity "0.5">
<!ENTITY wa_stroke_opacity_semi "0.5">
<!ENTITY wa_fill_opacity_semi "0.5">
