<!ENTITY motorway_casing_color   '#b95331'>
<!ENTITY trunk_casing_color      '#b93131'>
<!ENTITY primary_casing_color    '#8d4346'>
<!ENTITY secondary_casing_color  '#a37b48'>
<!ENTITY tertiary_casing_color   '#bbbbbb'>

<!ENTITY motorway_fill_color     '#eb7d54'>
<!ENTITY trunk_fill_color        '#e27272'>
<!ENTITY primary_fill_color	 '#e27272'>
<!ENTITY secondary_fill_color	 '#f6e856'>
<!ENTITY tertiary_fill_color	 '#ffffb3'>
<!ENTITY unclassified_fill_color '#ffffff'>
<!ENTITY motorway_overlay_color  '#f6e856'>
<!ENTITY trunk_overlay_color     '#f6f6f6'>
