"action_createpoi": POI oluşturuluyor
"hint_pointselected": nokta seçili\n(shift-tıkla yeni cizgi\nbaşlatmak için)
"action_movepoint": nokta taşınıyor
"hint_drawmode": yeni nokta için tıkla\nçizgi sona ermek için\nçift tıkla/ENTER bas
"hint_overendpoint": yolun son noktası\nbağlamak için tıkla\nbirleştirmek için shift-tıkla
"hint_overpoint": nokta üzerine\nbağlamak için tıkla
"gpxpleasewait": GPX izi işlenirken lütfen biraz bekleyin
"revert": Geri al
"cancel": Vazgeç
"prompt_revertversion": "Daha önce kaydedilmiş bir sürümüne dön:"
"tip_revertversion": Geri dönülecek sürümü seç
"action_movepoi": POI taşınıyor
"tip_splitway": Seçtiğin noktada yolu böl (X)
"tip_direction": Yolun yönü - ters yöne değiştirmek için tıkla
"tip_clockwise": saat yönünde dairesel yol - tersine dönmek için tıkla
"tip_anticlockwise": saatin ters yönünde dairesel yol - tersine dönmek için tıkla
"tip_noundo": Geri alınacak bir şey yok
"action_mergeways": iki yol birleştiriliyor
"tip_gps": GPS izlerini göster (G)
"tip_options": Ayarları değiştir (harita arka planını seç)
"tip_addtag": Yeni etiket ekle
"tip_addrelation": Bir ilişkiye ekle
"tip_repeattag": Etiketleri bir önceki seçtiğin yoldan kopyala (R)
"tip_alert": Bir hata oluştu - ayrıntılar için tıkla
"hint_toolong": "kilidi kaldırmak için yol fazla uzun:\nlütfen önce daha kısa\nyollara ayır"
"hint_loading": yollar yükleniyor
"prompt_welcome": "OpenStreetMap'e Hoşgeldin!"
"prompt_introduction": "Düzenlemek için aşağıdaki tuşlardan birini seç. 'Başla'ya tıklarsan, ana haritayı doğrudan düzenleyeceksin - değişiklikler genellikle Perşembe günleri gözükür. 'Deneme Tahtası'nı tıklarsan, değişikliklerin kaydedilmeyecektir, böylece düzenleme alıştırması yapabilirsin.\n\nOpenStreetMap'in kuralları anımsa:\n\n"
"prompt_dontcopy": Başka haritalardan kopyalamak kesinlikle yasaktır!
"prompt_accuracy": Hassasiyet önemlidir - bildiğin bölgeleri haritala
"prompt_enjoy": İyi eğlenceler!
"dontshowagain": Bu mesaj bir daha gösterme.
"prompt_start": OpenStreetMap ile harita çizmeye başla.
"prompt_practise": Harita üzerinde oyna - değişiklikler kaydedilmeyecek.
"practicemode": Deneme tahtası modu
"help": Yardım
"prompt_help": Potlatch, yani bu harita düzenleyici, nasıl kullanılır keşfet
"track": İz
"prompt_track": GPS izini, düzenlemek için (kilitli) bir yola dönüştür.
"action_deletepoint": bir nokta siliniyor
"deleting": siliniyor
"action_cancelchanges": "iptal ediliyor:"
"emailauthor": "\n\nLütfen bu hata konusunda richard\@systemeD.net'e bir e.posta at"
"error_connectionfailed": Maalesef OpenStreetMap sunucusuyla bağlantı koptu. Son değişiklikler kaydedilmedi.\n\nBir daha denemek ister misin?
"option_background": "Arkaplan:"
"option_fadebackground": Arkaplanı saydamlaştır
"option_thinlines": Tüm ölçeklerde ince çizgileri kullan
"option_custompointers": Kalem ve el işareti kullan
"tip_presettype": Menüde sunulan türleri seç
"action_waytags": yoldaki etiketler ayarlanıyor
"action_pointtags": noktadaki etiketler ayarlanıyor
"action_poitags": "POI'nin etiketleri ayarlanıyor"
"action_addpoint": yolun sonuna bir nokta ekleniyor
"add": Ekle
"prompt_addtorelation": ilişkiye $1 ekle
"prompt_selectrelation": Eklenecek mevcut bir ilişki seç, ya da yeni bir ilişki yarat.
"createrelation": Yeni bir ilişki yarat
"tip_selectrelation": Seçili rotaya ekle
"action_reverseway": yol tersine çevriliyor
"tip_undo": $1 Geri Al (Z)
"error_noway": $1 yolu bulunamıyor (belki atıdı) bu yüzden geri alamıyorum.
"error_nosharedpoint": $1 ve $2 yollarının paylaştıkları ortak bir nokta artık yok, bu yüzden bölmeyi geri alamıyorum.
"error_nopoi": "The POI cannot be found (perhaps you've panned away?) so I can't undo."
"prompt_taggedpoints": Bu yolun birkaç noktası etiketlenmiş. Gene de silinsin mi?
"action_insertnode": yola bir nokta ekleniyor
"action_splitway": yol bölünüyor
"editingmap": Harita düzenleme modu
"start": Başla
"play": Deneme Tahtası
"delete": Sil
"a_way": "yol: $1"
"a_poi": "POI: $1"
"action_moveway": yol taşınıyor
"way": Yol
"point": Nokta
"ok": Tamam
"existingrelation": Mevcut bir ilişkiye ekle
"findrelation": İçeren bir ilişki bul
"norelations": Çalışılan alanda ilişki yok
"advice_toolong": Kilidi kaldırmak için yol fazla uzun - lütfen önce daha kısa yollara ayır
"advice_waydragged": "Yol taşındı (geri almak için Z'ye bas)"
"advice_tagconflict": Etiketler eşleşmiyor - lütfen kontrol et
"advice_nocommonpoint": Yolların ortak noktası yok
"option_warnings": Uyarıları göster
"reverting": geri alınıyor
