#!/usr/bin/python2.4
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_ROUTE_POINTTYPE = descriptor.Descriptor(
  name='PointType',
  full_name='altitudeprofile.Route.PointType',
  filename='altitudeprofile.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='lat', full_name='altitudeprofile.Route.PointType.lat', index=0,
      number=1, type=2, cpp_type=6, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lon', full_name='altitudeprofile.Route.PointType.lon', index=1,
      number=2, type=2, cpp_type=6, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_ROUTE = descriptor.Descriptor(
  name='Route',
  full_name='altitudeprofile.Route',
  filename='altitudeprofile.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='point', full_name='altitudeprofile.Route.point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ROUTE.fields_by_name['point'].message_type = _ROUTE_POINTTYPE

class Route(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class PointType(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ROUTE_POINTTYPE
  DESCRIPTOR = _ROUTE

