<?php
/* 
 * the messages array is a from => to replacement array used by localization
 * copy this file and create a file named:
 * <your language 2lettercode>.php
 * And translate *ONLY* the strings after the => sign
 *
 */
$messages = array (
        'OpenStreetMap POI export' => 'OpenStreetMap POIs exportieren',
        'download free point of interest' => 'Freie Points Of Interest herunterladen',
        '1: POI type' => '1: POI-Typ',
        'Select the POI type' => 'Wählen Sie den POI-Typ',
        '2: Device' => '2: POI-Format',
        'Select the device or file type you want to download to' => 'Wählen Sie, in welchem Format Sie die POIs herunterladen möchten',
        '3: Export' => '3: Exportieren',
        'Download POI file' => 'POI-Datei herunterladen',
        'Select the type of POI you would like to download. Currently only one type can be selected.' => 'Wählen Sie, welchen POI-Typ Sie herunterladen möchten. Derzeit kann nur ein Typ gleichzeitig ausgewählt werden.',
        'Fuel' => 'Tankstelle',
        'ATM' => 'Geldautomat',
        'Speed camera' => 'Blitzer',
        'Bus stop' => 'Bushaltestelle',
        'Parking' => 'Parkplatz',
        'Bicycle parking' => 'Fahrradparkplatz',
        'Place of worship' => 'Anbetungsstätte',
        'Hospital' => 'Krankenhaus',
        'Supermarket' => 'Supermarkt',
        'Theatre' => 'Theater',
        'Police'=> 'Polizeistation',
        'Fire station' => 'Feuerwehr',
        'Post box' => 'Briefkästen',
        'Post office' => 'Postamt',
        'Recycling' => 'Recycling-Einrichtung',
        'Fast food' => 'Schnell-Restaurant',
        'Toilets' => 'Öffentliche Toilette',
        'Pub' => 'Kneipe',
        'Waste basket' => 'Mülleimer',
	'Cattle grid' => 'Weiderost',
        'Camp site' => 'Campingplatz',
        'Hotel' => 'Hotel',
        'Museum' => 'Museum',
        'Zoo' => 'Tierpark',
        'Castle' => 'Schloss',
        'Windmill' => 'Windmühle',
        'Lighthouse' => 'Leuchtturm',
        'Watermill' => 'Wassermühle',
        'Water tower' => 'Wasserturm',
        'Nightclub' => 'Disco',
        'Stripclub' => 'Stripclub',
        'Next' => 'Weiter',
        'Previous' => 'Zurück',
        'Select the device or file type you want to download the POI in' => 'Wählen Sie, in welchem Format Sie die POIs herunterladen möchten',
        'TomTom overlay (ov2)' => 'TomTom overlay (ov2)',
        'Garmin (csv)' => 'Garmin (csv)',
        'GPS Exchange format (gpx)' => 'GPS Exchange format (gpx)',
        'Google Earth (kml)' => 'Google Earth (kml)',
        'OpenStreetMap (osm)' => 'OpenStreetMap (osm)',
	'OziExplorer (wpt)' => 'OziExplorer (wpt)',
        'The file is ready for download.' => 'Die Datei steht zum Download bereit.',
        'Poi type' => 'POI-Typ',
        'Device type' => 'Datenformat',
        'Download' => 'Herunterladen',
        'Poi Export' => 'POI-Export',
        'data' => 'data',
        'OpenStreetMap' => 'OpenStreetMap',
        'community' => 'Gemeinschaft',
        'Created by' => 'Erstellt durch',
        'and' => 'und'

        );
?>
