"action_createpoi": создание точки интереса (POI)
"hint_pointselected": точка выбрана\n(кликните с нажатым Shift на точку\nчтобы начать новую линию)
"action_movepoint": перемещение точки
"hint_drawmode": кликните для добавления точки,\nдвойной клик или Enter\nчтобы закончить линию
"hint_overendpoint": над конечной точкой\nclick для соединения\nshift-click для слияния
"hint_overpoint": над точкой\nclick для соединения"
"gpxpleasewait": Пожалуйста, подождите — GPX-треки обрабатываются.
"revert": Восстановить
"cancel": Отмена
"prompt_revertversion": "Восстановить ранее сохраненную версию:"
"tip_revertversion": Выберите версию для восстановления
"action_movepoi": перемещение точки интереса (POI)
"tip_splitway": Разделить линию в текущей точке (X)
"tip_direction": Направление линии — изменить на противоположное
"tip_clockwise": Замкнутая линия по часовой стрелке - изменить на противоположное
"tip_anticlockwise": Замкнутая линия против часовой стрелки - изменить на противоположное
"tip_noundo": Нечего отменять
"action_mergeways": соединение двух линий
"tip_gps": Показать GPS треки (G)
"tip_options": Задать настройки (выбрать карту-подложку)
"tip_addtag": Добавить новый тег
"tip_addrelation": Добавить новое отношение (relation)
"tip_repeattag": Повторить теги с предыдущей выбранной линии (R)
"tip_alert": Произошла ошибка — нажмите для получения подробностей
"hint_toolong": "слишком длинная линия для разблокировки:\пожалуйста, разбейте ее\nна более короткие линии"
"hint_loading": загрузка линий
"prompt_welcome": Добро пожаловать в OpenStreetMap!
"prompt_introduction": "Выберите кнопку. Если вы нажмёте «Старт», вы начнёте редактировать карту. Основная карта обновляется по средам. Если вы нажмёте «Тренировка», ваши изменения на карте сохраняться не будут и вы сможете практиковаться в редактировании.\n\nЗапомните основные правила OpenStreetMap:\n\n"
"prompt_dontcopy": Не копируйте информацию с других карт
"prompt_accuracy": Точность важна. Составляйте карты только для тех мест, в которых вы были.
"prompt_enjoy": Приятного вам времяпровождения!
"dontshowagain": Не показывать это сообщение снова.
"prompt_start": Начать редактировать карту OpenStreetMap.
"prompt_practise": Тренировочное редактирование — ваши изменения не будут сохранены.
"practicemode": Тренировочный режим
"help": Помощь
"prompt_help": Узнать, как пользоваться редактором.
"track": Трек
"prompt_track": Конвертировать GPS-трек в линию(заблокированную), для редактирования.
"action_deletepoint": удаление точки
"deleting": удаление
"action_cancelchanges": отмена изменений к
"emailauthor": "\n\nПожалуйста, отправьте сообщение об ошибке (на английском языке) на электронную почту: richard\@systemeD.net, с указанием того, какие действия вы совершали."
"error_connectionfailed": "Извините, соединение с сервером OpenStreetMap разорвано. Все текущие изменения не были сохранены.\n\nПопробовать ещё раз?"
"option_background": "Фон:"
"option_fadebackground": Светлый фон
"option_thinlines": Использовать тонкие линии на всех масштабах
"option_custompointers": Использовать курсоры пера и руки
"tip_presettype": Выберите, какой набор тегов отображать в меню.
"action_waytags": установку тегов для линии
"action_pointtags": установку тегов для точки
"action_poitags": установку тегов для точки интереса (POI)
"action_addpoint": добавление точки в конец линии
"add": Добавить
"prompt_addtorelation": Добавить $1 в отношение
"prompt_selectrelation": Выберите существующее отношение или создайте новое.
"createrelation": Создать новое отношение
"tip_selectrelation": Добавить в выбранное отношение
"action_reverseway": изменение направления линии
"tip_undo": Отменить $1 (Z)
"error_noway": Линия $1 не найдена (возможно вы отошли в сторону?), поэтому невозможно отменить.
"error_nosharedpoint": Линии $1 и $2 больше не содержат общих точек, поэтому невозможно отменить разделение.
"error_nopoi": Точка интереса(POI) не найдена (возможно вы отошли в сторону?), поэтому невозможно отменить.
"prompt_taggedpoints": Некоторые точки данной линии содержат теги. Действительно удалить?
"action_insertnode": добавление точки в линию
"action_splitway": разбиение линии
"editingmap": Редактирование карты
"start": Старт
"play": Тренировка
"delete": Удалить
"a_way": $1 линия
"a_poi": $1 точка интереса (POI)
"action_moveway": перемещение линии
"way": Линия
"point": Точка
"ok": Ok
"existingrelation": Добавить в существующее отношение
"findrelation": Найти отношения
"norelations": Нет отношений в текущей области
"advice_toolong": Длина слишком велика. Пожалуйста, разделите на более короткие линии
"advice_waydragged": Линия передвинута (Z для отмены)
"advice_tagconflict": Тэги не совпадают, пожалуйста проверьте (Z для отмены)
"advice_nocommonpoint": Линии не имеют общей точки
"option_warnings": Показывать всплывающие предупреждения
"reverting": возвращается
"prompt_helpavailable": Присутствуют несохранённые изменения. (Чтобы записать изменения в Potlatch, снимите выделение с текущей точки или линии)
