
<P>Lasted update time: <?php print $lastUpdate; ?></p>

<P>Have you added your local baseball fields yet? <a href="http://wiki.openstreetmap.org/wiki/Big baseball project 2011" title="Details on the OpenStreetMap wiki">Find out more</a></p>

<p>This system was set to pick up on baseball related edits (sport=baseball tag) in OpenStreetMap each minute but with a delay of several minutes, however there may also be outages causing much longer delays. If you've done some baseball field mapping, wait a little while (or go do a little more!) before refreshing this page </p>

<P>By Harry Wood. <a href="./baseball-edits.csv">Data live updated for this display available in csv</a> or <a href="./baseball-edits.db">as an sqlite3 db file</a>. <a href="http://svn.openstreetmap.org/applications/viewer/diffreader/baseball">php source code for the display</a> (very simple so far. <a href="http://harrywood.co.uk/contact-harry.php">Patches welcome</a>) <a href="../diffreader.rb">ruby script for finding matching edits in the minutely diffs</a> 


</body>
</html>
