standard_settings: &standard_settings
  # The maximum area you're allowed to request, in square degrees
  max_request_area: 0.25
  # Number of GPS trace/trackpoints returned per-page
  tracepoints_per_page: 5000
  # Maximum number of nodes
  max_number_of_nodes: 50000
 
development:
  <<: *standard_settings

production:
  <<: *standard_settings

test:
  <<: *standard_settings
