Document: openstreetmap
Title: Debian openstreetmap Manual
Author: <insert document author here>
Abstract: This manual describes what openstreetmap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openstreetmap/openstreetmap.sgml.gz

Format: postscript
Files: /usr/share/doc/openstreetmap/openstreetmap.ps.gz

Format: text
Files: /usr/share/doc/openstreetmap/openstreetmap.text.gz

Format: HTML
Index: /usr/share/doc/openstreetmap/html/index.html
Files: /usr/share/doc/openstreetmap/html/*.html

  
