/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TraceyPropertiesDialog.java
 *
 * Created on 26-Nov-2009, 22:24:05
 */

package org.openstreetmap.tracey;

import java.util.prefs.Preferences;

import org.jdesktop.application.Action;


/**
 *
 * @author Jono
 */
public class TraceyPropertiesDialog extends javax.swing.JDialog {

	private String tags;
	private String description;
	private PrivacyListModel privacyList = new PrivacyListModel();
	private int returnStatus;

	public static final int UPLOAD = 1;
	public static final int CANCEL = 0;

    /** Creates new form TraceyPropertiesDialog */
    public TraceyPropertiesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        descriptionLabel = new javax.swing.JLabel();
        tagsTextField = new javax.swing.JTextField();
        tagsLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        privacyComboBox = new javax.swing.JComboBox();
        privacyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.openstreetmap.tracey.TraceyApp.class).getContext().getResourceMap(TraceyPropertiesDialog.class);
        setTitle(resourceMap.getString("descriptionForm.title")); // NOI18N
        setModal(true);
        setName("descriptionForm"); // NOI18N
        setResizable(false);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setFont(new java.awt.Font("Tahoma", 0, 11));
        descriptionTextArea.setRows(5);
        descriptionTextArea.setText(Preferences.userNodeForPackage(this.getClass()).get("lastDescription",""));
        descriptionTextArea.setToolTipText(resourceMap.getString("descriptionTextArea.toolTipText")); // NOI18N
        descriptionTextArea.setName("descriptionTextArea"); // NOI18N
        jScrollPane1.setViewportView(descriptionTextArea);

        descriptionLabel.setLabelFor(descriptionTextArea);
        descriptionLabel.setText(resourceMap.getString("descriptionLabel.text")); // NOI18N
        descriptionLabel.setFocusable(false);
        descriptionLabel.setName("descriptionLabel"); // NOI18N

        tagsTextField.setText(Preferences.userNodeForPackage(this.getClass()).get("lastDescription",""));
        tagsTextField.setToolTipText(resourceMap.getString("tagsTextField.toolTipText")); // NOI18N
        tagsTextField.setName("tagsTextField"); // NOI18N

        tagsLabel.setLabelFor(tagsTextField);
        tagsLabel.setText(resourceMap.getString("tagsLabel.text")); // NOI18N
        tagsLabel.setFocusable(false);
        tagsLabel.setName("tagsLabel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(org.openstreetmap.tracey.TraceyApp.class).getContext().getActionMap(TraceyPropertiesDialog.class, this);
        okButton.setAction(actionMap.get("doUpload")); // NOI18N
        okButton.setText(resourceMap.getString("OK.text")); // NOI18N
        okButton.setName("OK"); // NOI18N

        cancelButton.setAction(actionMap.get("cancelUpload")); // NOI18N
        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N

        privacyComboBox.setModel(privacyList);
        privacyComboBox.setName("privacyList"); // NOI18N

        privacyLabel.setLabelFor(privacyComboBox);
        privacyLabel.setText(resourceMap.getString("privacyLabel.text")); // NOI18N
        privacyLabel.setFocusable(false);
        privacyLabel.setName("privacyLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(descriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tagsLabel)
                            .addComponent(privacyLabel))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(privacyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tagsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tagsLabel)
                    .addComponent(tagsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(privacyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(privacyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TraceyPropertiesDialog dialog = new TraceyPropertiesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

	public String getDescription() {
		return this.description;
	}

	public String getTags() {
		return this.tags;
	}

	public Privacy getPrivacy() {
		return this.privacyList.getSelectedItem();
	}

	@Action
	public void doUpload() {
		this.tags = tagsTextField.getText();
		this.description = descriptionTextArea.getText();
		doClose(UPLOAD);
	}

	@Action
	public void cancelUpload() {
		doClose(CANCEL);
	}

	private void doClose(int retStatus) {
		returnStatus = retStatus;
		setVisible(false);
		dispose();
    }

	/** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
	public int getReturnStatus() {
		return returnStatus;
	}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox privacyComboBox;
    private javax.swing.JLabel privacyLabel;
    private javax.swing.JLabel tagsLabel;
    private javax.swing.JTextField tagsTextField;
    // End of variables declaration//GEN-END:variables

}
