/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TraceyPreferencesBox.java
 *
 * Created on 12-Nov-2009, 22:07:59
 */

package org.openstreetmap.tracey;

import java.util.prefs.*;
import org.jdesktop.application.Action;

/**
 *
 * @author Jonathan Bennett
 */
public class TraceyPreferencesBox extends javax.swing.JDialog {

	public static final String USERNAME = "username";
	public static final String PASSWORD = "password";
	public static final String APIURI = "apiuri";

    /** Creates new form TraceyPreferencesBox */
    public TraceyPreferencesBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
		getRootPane().setDefaultButton(okButton);
		Preferences traceyPrefs = Preferences.userNodeForPackage(this.getClass());
		userNameField.setText(traceyPrefs.get(USERNAME, "pinky"));
		passwordField.setText(traceyPrefs.get(PASSWORD, "perky"));
		uriField.setText(traceyPrefs.get(APIURI, "http://www.openstreetmap.org/api/0.6/"));
    }

	@Action public void closeTraceyPreferencesBox() {
		dispose();
	}

	@Action public void savePreferences() {
		Preferences traceyPrefs = Preferences.userNodeForPackage(this.getClass());
		traceyPrefs.put(USERNAME, userNameField.getText());
		traceyPrefs.put(PASSWORD, new String(passwordField.getPassword()));
		traceyPrefs.put(APIURI, uriField.getText());
		dispose();
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameField = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        uriLabel = new javax.swing.JLabel();
        uriField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.openstreetmap.tracey.TraceyApp.class).getContext().getResourceMap(TraceyPreferencesBox.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        userNameField.setText(resourceMap.getString("userNameField.text")); // NOI18N
        userNameField.setToolTipText(resourceMap.getString("userNameField.toolTipText")); // NOI18N
        userNameField.setName("userNameField"); // NOI18N
        userNameField.setNextFocusableComponent(passwordField);

        userNameLabel.setLabelFor(userNameField);
        userNameLabel.setText(resourceMap.getString("userNameLabel.text")); // NOI18N
        userNameLabel.setToolTipText(resourceMap.getString("userNameLabel.toolTipText")); // NOI18N
        userNameLabel.setName("userNameLabel"); // NOI18N

        passwordLabel.setLabelFor(passwordField);
        passwordLabel.setText(resourceMap.getString("passwordLabel.text")); // NOI18N
        passwordLabel.setToolTipText(resourceMap.getString("passwordLabel.toolTipText")); // NOI18N
        passwordLabel.setName("passwordLabel"); // NOI18N

        passwordField.setText(resourceMap.getString("passwordField.text")); // NOI18N
        passwordField.setName("passwordField"); // NOI18N
        passwordField.setNextFocusableComponent(okButton);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(org.openstreetmap.tracey.TraceyApp.class).getContext().getActionMap(TraceyPreferencesBox.class, this);
        cancelButton.setAction(actionMap.get("closeTraceyPreferencesBox")); // NOI18N
        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.setNextFocusableComponent(userNameField);

        okButton.setAction(actionMap.get("savePreferences")); // NOI18N
        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setMaximumSize(new java.awt.Dimension(67, 23));
        okButton.setMinimumSize(new java.awt.Dimension(67, 23));
        okButton.setName("okButton"); // NOI18N
        okButton.setNextFocusableComponent(cancelButton);

        uriLabel.setLabelFor(uriField);
        uriLabel.setText(resourceMap.getString("uriLabel.text")); // NOI18N
        uriLabel.setName("uriLabel"); // NOI18N

        uriField.setText("http://www.openstreetmap.org/api/"); // NOI18N
        uriField.setToolTipText(resourceMap.getString("uriField.toolTipText")); // NOI18N
        uriField.setName("uriField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                            .addComponent(uriLabel))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(uriField, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uriLabel)
                    .addComponent(uriField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TraceyPreferencesBox dialog = new TraceyPreferencesBox(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField uriField;
    private javax.swing.JLabel uriLabel;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables

}
