osmcut: osmcut.c
	cc -g -o osmcut osmcut.c -DUSE_ARRAY -DLARGEFILE_SOURCE -I/usr/include/glib-2.0 -lglib-2.0 -I /usr/lib/glib-2.0/include

osmcut-hash: osmcut.c
	cc -g -o osmcut-hash osmcut.c -DLARGEFILE_SOURCE -I/usr/include/glib-2.0 -lglib-2.0 -I /usr/lib/glib-2.0/include 


