"action_createpoi": 建立一個 POI
"hint_pointselected": 已選擇一個 point\n(按 shift再點選 point 可\n開始畫新的線段)
"action_movepoint": 移動 point
"hint_drawmode": 單擊加入新的 point\n雙擊/Enter\n可結束此線段
"hint_overendpoint": 在結束 point 上\n單擊會製作交叉\n按 shift 再點選會合併
"hint_overpoint": 在 point 上\n單擊會製作交叉
"gpxpleasewait": 在處理 GPX 追蹤時請稍候。
"revert": 回復
"cancel": 取消
"prompt_revertversion": "回復到較早儲存的版本:"
"tip_revertversion": 選擇要回復的版本
"action_movepoi": 移動 POI
"tip_splitway": 在選取的 point 將路徑分開 (X)
"tip_direction": 路徑的方向 - 單擊可反轉方向
"tip_clockwise": Clockwise circular way - click to reverse
"tip_anticlockwise": Anti-clockwise circular way - click to reverse
"tip_noundo": 沒有可復原的項目
"action_mergeways": 正在合併兩條路徑
"tip_gps": 顯示 GPS 追蹤 (G)
"tip_options": 設定選項 (選擇地圖背景)
"tip_addtag": 加入新的標籤
"tip_addrelation": 加入關係
"tip_repeattag": 重複前一次選取路徑的標籤 (R)
"tip_alert": 發生錯誤 - 點選以取得詳細資訊
"hint_toolong": "路徑太長而無法解除鎖定:\n請將它分離為\n較短的路徑"
"hint_loading": 正在載入路徑
"prompt_welcome": 歡迎使用 OpenStreetMap！
"prompt_introduction": "選擇下列按鈕進行編輯。如果您選擇「開始」，將會直接編輯地圖 - 所做的變更通常會在每週四顯示出來。如果您選擇「練習」，您的變更將不會儲存，所以可以用來練習編輯。\n\n請記得 OpenStreetMap 的黃金定律:\n\n"
"prompt_dontcopy": 不要複製其他地圖
"prompt_accuracy": 準確性很重要 - 只繪製您到過的地方
"prompt_enjoy": 好好享受！
"dontshowagain": 不要再顯示這個訊息
"prompt_start": 開始繪製 OpenStreetMap。
"prompt_practise": 練習製圖 - 您的變更不會被儲存。
"practicemode": 練習模式
"help": 求助
"prompt_help": 了解如何使用 Potlatch，這個地圖編輯器。
"track": 追蹤
"prompt_track": 將您的 GPS 追蹤轉換為 (鎖定的) 路徑以便編輯。
"action_deletepoint": 正在刪除 point
"deleting": 刪除中
"action_cancelchanges": 取消變更：
"emailauthor": \n\n請寄一封程式錯誤報告的電子郵件給 richard\@systemeD.net，並說明當時您在做什麼動作。
"error_connectionfailed": 抱歉 - 對 OpenStreetMap 伺服器的連線失敗了。任何最新的變更將不會儲存。\n\n您是否要再試一次？
"option_background": "背景:"
"option_fadebackground": 淡化背景
"option_thinlines": 在所有縮放等級使用細線
"option_custompointers": Use pen and hand pointers
"tip_presettype": 選擇在選擇中要提供哪種類型的預先設定。
"action_waytags": 設定路徑上的標籤
"action_pointtags": 設定 point 上的標籤
"action_poitags": 設定 POI 上的標籤
"action_addpoint": 在路徑的結尾加上節點
"add": 加入
"prompt_addtorelation": 將 $1 加入為關係
"prompt_selectrelation": 選擇一個既存的關係來加入，或是建立新的關係。
"createrelation": 建立新的關係
"tip_selectrelation": 加入到選取的路線
"action_reverseway": 反轉路徑
"tip_undo": 復原 $1 (Z)
"error_noway": "找不到路徑 $1 (perhaps you've panned away?) ，因此我不能復原它。"
"error_nosharedpoint": 路徑 $1 和 $2 不再分享共同 point，因此我無法復原此分離動作。
"error_nopoi": "The POI cannot be found (perhaps you've panned away?) so I can't undo."
"prompt_taggedpoints": 這個路徑上的部分 point 已有標籤。確定要刪除？
"action_insertnode": 在路徑中加入節點
"action_splitway": 分離一條路徑
"editingmap": 編輯地圖
"start": 開始
"play": 練習
"delete": 刪除
"a_way": $1 路徑
"a_poi": $1 POI
"action_moveway": 移動路徑
"way": 路徑
"point": Point
"ok": 確定
"existingrelation": 加入既存的關係
"findrelation": 尋找關係有包含
"norelations": 在目前的區域中沒有此關係
"advice_toolong": 路徑太長而無法解除鎖定 - 請將它分離為較短的路徑
"advice_waydragged": 拖曳的路徑 (按 Z 復原)
"advice_tagconflict": 標籤不符 - 請檢查
"advice_nocommonpoint": 這些路徑不再分享共同 point
"option_warnings": 顯示浮動式警示
"reverting": 正在反轉
