"action_createpoi": lave et POI (interessant punkt)
"hint_pointselected": punkt valgt\n(shift+klik punktet for at\nstarte en ny linie)
"action_movepoint": flytter et punkt
"hint_drawmode": klik for at tilføje punkt\ndobbeltklik eller enter\nfor at afslutte linie
"hint_overendpoint": over endepunkt\nklik for at forbinde\nshift+klik for at slå sammen til en
"hint_overpoint": over punkt\nklik for at forbinde
"gpxpleasewait": Vent venligst mens GPX sporet behandles.
"revert": Rette tilbage
"cancel": Afbryd
"prompt_revertversion": "Ret tilbage til tidligere lagret version:"
"tip_revertversion": Vælg versionen der skal rettes tilbage til
"action_movepoi": flytter et POI (interessant punkt)
"tip_splitway": Del vej i valgt punkt (X)
"tip_direction": Vejretning, klik for at vende
"tip_clockwise": Cirkulær vej med uret, klik for at vende
"tip_anticlockwise": Cirkulær vej mod uret, klik for at vende
"tip_noundo": Intet at fortryde
"action_mergeways": slår to veje sammen
"tip_gps": Vis GPS spor (G)
"tip_options": Sæt indstillinger (vælg kortbaggrund)
"tip_addtag": Tilføj et tag
"tip_addrelation": Føj til en relation
"tip_repeattag": Gentag tags fra senest valgte vej (R)
"tip_alert": Der opstod en fejl, klik for detaljer
"hint_toolong": "for lang til at låse op:\nopdel venligst\ni mindre veje"
"hint_loading": henter veje
"prompt_welcome": Velkommen til OpenStreetMap!
"prompt_introduction": "Vælg en knap nedenfor for at redigere. Hvis du vælger 'Start' redigerer du kortet direkte, ændringer bliver normalt synlige hver torsdag. Hvis du vælger 'Øve' gemmes ændringer ikke, så kan du øve dig i at redigere.\nHusk OpenStreetMaps gyldne regler:\n\n"
"prompt_dontcopy": Ikke kopier fra andre kort
"prompt_accuracy": Nøjagtighed er vigtig, kortlæg kun steder du har besøgt
"prompt_enjoy": Og hav det morsomt!
"dontshowagain": Vis ikke denne besked igen
"prompt_start": Begynd at kortlægge med OpenStreetMap.
"prompt_practise": Øv i kortlæging, ændringer bliver ikke lagret.
"practicemode": Øvelsestilstand
"help": Hjælp
"prompt_help": Find ud af hvordan du bruger Potlatch, programmet til kortredigering.
"track": Spor
"prompt_track": Overfør dine GPS-spor til (låste) veje for redigering.
"action_deletepoint": sletter et punkt
"deleting": sletter
"action_cancelchanges": afbryder ændringer af
"emailauthor": \n\nVenligst send en e-mail (på engelsk) til richard\@systemeD.net med en fejlrapport, og forklar hvad du gjorde da det skete.
"error_connectionfailed": "Beklager - forbindelsen til OpenStreetMap-serveren fejlede, eventuelle nye ændringer er ikke blevet gemt.\n\nVil du prøve igen?"
"option_background": "Baggrund:"
"option_fadebackground": Fjern baggrund
"option_thinlines": Brug tynde linier uanset skalering
"option_custompointers": Brug pen- og håndvisere
"tip_presettype": Vælg hvilke type forhåndsinstillinger som er tilgænglige i menuen
"action_waytags": sætter tags på en vej
"action_pointtags": sætter tags på et punkt
"action_poitags": sætter tags på et POI (interessant punkt)
"action_addpoint": tilføjer et punkt til enden af en vej
"add": Tilføj
"prompt_addtorelation": Tilføj $1 til en relation
"prompt_selectrelation": Vælg en eksisterende relation for at føje til denne, eller lav en ny relation
"createrelation": Lav en ny relation
"tip_selectrelation": Føj til den valgte rute
"action_reverseway": vend retningen på en vej
"tip_undo": Fortryd $1 (Z)
"error_noway": Fandt ikke vejen $1 så det er ikke muligt at fortryde. (Måske er den ikke på skærmen længere?)
"error_nosharedpoint": Vejene $1 og $2 deler ikke noget punkt længere, så det er ikke muligt at fortryde delingen.
"error_nopoi": Fandt ikke POI-et, så det er ikke muligt at fortryde. (Måske er den ikke på skærmen længere?)
"prompt_taggedpoints": Nogle af punktene på denne vej har tags. Vil du virkelig slette?
"action_insertnode": tilføj et punkt på vejen
"action_splitway": del en vej
"editingmap": Redigerer kort
"start": Start
"play": Øve
"delete": Slet
"a_way": $1 en vej
"a_poi": $1 et POI
"action_moveway": flytter en vej
"way": Vej
"point": Punkt
"ok": Ok
"existingrelation": Føj til en eksisterende relation
"findrelation": Find en relation som indeholder
"norelations": Ingen relationer i området på skærmen
